mbta/api

apps/state_mediator/config/test.exs, apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
These tests have been replaced with validations when we create the GTFS
file. Removing them means we don't have to update both the API and the GTFS
repo when we add new data to GTFS.
Comes out of work for the new bus/subway rating.
=> remove unneeded integration tests

apps/api_web/lib/api_web/controllers/route_pattern_controller.ex, apps/api_web/lib/api_web/controllers/shape_controller.ex, apps/api_web/lib/api_web/router.ex, apps/api_web/lib/api_web/views/route_pattern_view.ex, apps/api_web/test/api_web/controllers/route_pattern_controller_test.exs, apps/model/lib/model/route_pattern.ex, apps/parse/lib/parse/route_patterns.ex, apps/parse/test/parse/route_patterns_test.exs, apps/state/lib/state.ex, apps/state/lib/state/route_pattern.ex, apps/state_mediator/lib/gtfs_decompress.ex
Ticket: [create new endpoint for route_patterns](https://app.asana.com/0/810933294009540/972585955714941)
- `/route-patterns`
- `/route-patterns/{id}`
- `...?include=route,representative_trip`
- `...?filter[id]=`
- `...?filter[route]=`
This just contains the core stuff needed for `/route-patterns`. More filtering and including from trips and routes is split into [route_patterns api, phase II](https://app.asana.com/0/810933294009540/1110437930242554) to keep this PR manageable
=> route pattern api endpoint

apps/api_web/lib/api_web/controllers/schedule_controller.ex
Ticket: [correct API schedule documentation (both times are always present)](https://app.asana.com/0/810933294009540/1111071118126585)
=> Make arrival_time and departure_time not nullable in swagger

apps/api_web/lib/api_web/router.ex, apps/api_web/lib/api_web/templates/client_portal/portal/landing.html.eex
Ticket: [Add link to API repo in Swagger documentation](https://app.asana.com/0/810933294009540/935867925516816)
Since there is no separate swagger section for the source repo link ([ref](https://swagger.io/specification/#infoObject)), I've added it to the `description` field.
=> Add link to API repo in Swagger documentation

apps/api_web/lib/api_web/controllers/service_controller.ex, apps/api_web/lib/api_web/params.ex, apps/api_web/test/api_web/controllers/facility_controller_test.exs, apps/api_web/test/api_web/params_test.exs
Partially reverts #11 
This leaves the function calls intact so that they can be re-implemented with
the future version-based approach.
=> revert validation of parameters

README.md
I was able to get the project up and running locally by following the README, the api_accounts README was especially detailed! 🎉 
I was able to start developing locally without step 4. I'm assuming this step needs updating and that state_mediator is set up already by default.
=> Remove state mediator setup from README

apps/state/config/config.exs
The newest data from HASTUS uses these new shape IDs.
=> additional ignored shapes for Green-B

apps/api_web/config/prod.exs, apps/api_web/lib/api_web/plugs/authenticate.ex, apps/api_web/test/api_web/plugs/authenticate_test.exs
We already log it as a part of the metadata, so we don't need to log it again as a parameter.
=> don't log the API key as a part of params

apps/state/lib/state/helpers.ex, apps/state/lib/state/stops_on_route.ex, apps/state/test/state/stops_on_route_test.exs, apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
The [101](https://www.mbta.com/schedules/101/line?direction_id=0) has a few different variants (not all represented as shapes), and it ends up with a confusing behavior when looking at what stops the API considers to be a part of that route during the week.
This change is to stop using the shapes to determine the stops on a day, and instead to use the route patterns. This still allows us to ignore shuttles and other disruptions, but does include atypical patterns which received negative shape priorities in the past.
We keep the existing shape code around, as it's used to provide the list of stops for each shape.
Product/design sign-off:
=> use Route Patterns to decide what stops are on routes

apps/api_web/lib/api_web/plugs/rate_limiter.ex, apps/api_web/lib/api_web/rate_limiter.ex, apps/api_web/lib/api_web/rate_limiter/ets.ex, apps/api_web/lib/api_web/rate_limiter/limiter.ex, apps/api_web/lib/api_web/rate_limiter/memcache.ex, apps/api_web/lib/api_web/router.ex, apps/api_web/test/api_web/plugs/rate_limiter_test.exs, apps/api_web/test/api_web/rate_limiter/memcache_test.exs, apps/api_web/test/api_web/rate_limiter_test.exs, apps/events/lib/events.ex
* Adds new headers "x-ratelimit-limit", "x-ratelimit-remaining", "x-ratelimit-reset".
* Changes rate limiting to use time-based buckets rather than memcached ttl, so that we know the time when limits reset.
=> Add rate limit headers

apps/model/lib/model/stop.ex, apps/model/test/model/stop_test.exs, apps/state/lib/state/stop/list.ex, apps/state/mix.exs, apps/state/test/state/stop/list_test.exs
We obviously can't search for a stop without a location, so filter out those
stops when building the tree. The reason this is implemented as a property
test instead of a simple test is that it requires multiple stops to trigger
the crash.
=> fix: filter out stops w/o location when building R* tree

apps/api_web/lib/api_web/params.ex, apps/api_web/test/api_web/params_test.exs
Note that this PR will allow users to include exactly the same relationship path multiple times: e.g. https://api-v3.mbta.com/route-patterns/Red-1-1?include=representative_trip.service,representative_trip.service. (This would return the same response as if it were only included once.)
Note also that, currently, there is no validation of anything besides the first part of a relationship path. This is not changed by the current PR. e.g. https://api-v3.mbta.com/route-patterns/Red-1-1?include=representative_trip.bad_path will not error, and will return the same response as https://api-v3.mbta.com/route-patterns/Red-1-1?include=representative_trip. I believe it would require significant changes to change this: in the route pattern controller, we know what includes are permitted for route …
=> Allow including the same resource twice

apps/api_web/lib/api_web/controllers/live_facility_controller.ex
* The only filter available for `/live-facilities` is `filter[id]`
* Confirmed that there is no other endpoint which has an empty filter in the swagger docs.
=> Fix swagger docs for /live-facilities

apps/api_web/lib/api_web/controllers/route_controller.ex, apps/api_web/lib/api_web/controllers/vehicle_controller.ex, apps/api_web/lib/api_web/swagger_helpers.ex
Confirmed that you can always filter by multiple `route_type`, updated swagger docs to reflect this.
=> Make filter[route_type] documentation consistent

apps/api_web/lib/api_web/views/route_pattern_view.ex, apps/api_web/test/api_web/controllers/route_pattern_controller_test.exs
`representative_trip` `data` field should be a single trip, not a list of trips of length 1.
=> Fix representative_trip relationship for /route-patterns

apps/api_web/lib/api_web/api_controller_helpers.ex, apps/api_web/lib/api_web/params.ex, apps/api_web/test/api_web/api_controller_helpers_test.exs, apps/api_web/test/api_web/params_test.exs
`includes[key]` in a query will cause includes to be a map rather than a string. In this case:
- Don't crash in `ApiControllerHelpers.split_include`, then
- Catch and return error in `Params.validate_includes`
=> Handle case where includes is a map

apps/state/config/config.exs
Without this change, we would return Haymarket and North Station as stops on the `Green-D` route.
=> Add priority override for new Green-D to North Station shape

apps/api_web/lib/api_web/controllers/schedule_controller.ex, apps/api_web/lib/api_web/views/schedule_view.ex, apps/api_web/test/api_web/controllers/schedule_controller_test.exs, apps/api_web/test/api_web/views/schedule_view_test.exs, apps/state/lib/state.ex
Ticket: [sorting schedules in earlier versions should work as if both values are present](https://app.asana.com/0/810933294009540/1126222348431249/f)
=> Added logic to handle nil arrival/departure schedule times when sorting

apps/api_web/lib/api_web/templates/admin/accounts/user/show.html.eex
At the moment, you need to click on each key to see the version from the
admin side. This adds the version to the table so you can see an overview.
=> feat: show API version in admin page

apps/api_web/lib/api_web/api_controller_helpers.ex, apps/api_web/lib/api_web/api_view_helpers.ex, apps/api_web/lib/api_web/event_stream/diff_server.ex, apps/api_web/lib/api_web/views/facility_view.ex, apps/api_web/test/api_web/api_controller_helpers_test.exs, apps/api_web/test/api_web/views/facility_view_test.exs
Ticket: [Facility name is not fetched for older API versions](https://app.asana.com/0/810933294009540/1126993432964133/f)
```bash
$ curl -g "http://localhost:4000/stops/place-brntn?fields[facility]=name,type&include=facilities" |jsonpp
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  7207  100  7207    0     0   1997      0  0:00:03  0:00:03 --:--:--  1996
{
"data": {
"attributes": {
"address": "197 Ivory St, Braintree, MA 02184",
"description": null,
"latitude": 42.207854,
"location_type": 1,
"longitude": -71.001138,
"name": "Braintree",
"platform_code": null,
"platform_name": null,
"wheelchair_boarding": 1
},
"id": "place-brntn",
"links": {
"self": "/stops/place-brntn"
},
"relationships": {
"child_stops": {}, …
```
=> Support for fetching facility name for older API versions

apps/api_web/lib/api_web/rate_limiter/memcache.ex, apps/api_web/lib/api_web/rate_limiter/memcache/supervisor.ex
Previously, we only kept open one connection to Memcache. However, under high
traffic this can cause a queue for the single connection. This creates a
small worker pool of connections (managed by a Registry), and uses that to
pick a random child for each request.
Pulled out of #62.
=> feat: multiple connections to Memcache

apps/state/lib/state.ex, apps/state/test/state_test.exs
`valid_order_by_key?` is only called with key `:distance` if `opts_map` is missing one or both of `:latitude` or `:longitude`, so it should always be invalid rather than always being valid.
=> Fix distance always a valid sort

apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
Ticket: [change API to always use parent stations once that PR lands](https://app.asana.com/0/810933294009540/1116203090371271/f)
Not sure if I fully understood the context as I was not part of parent stops discussions. Please let me know if I missed anything.
=> Switch integration tests to use parent stop ids

apps/api_web/lib/api_web/views/prediction_view.ex, apps/api_web/lib/api_web/views/schedule_view.ex, apps/state/lib/state/prediction.ex, apps/state/lib/state/schedule.ex, apps/state/test/state/prediction_test.exs, apps/state/test/state/schedule_test.exs
Ticket: [API: investigate slow prediction queries](https://app.asana.com/0/810933294009540/1126090013342360/f)
Before vs after:
```bash
Levs-MBP:~ lev$ for i in {1..10}; do curl -g "http://localhost:4000/predictions?filter[route]=Red,Orange,Green-B,Green-C,Green-D,Green-E,Blue,Mattapan,741,742,743,751,749&include=schedule,stop,route,trip,vehicle&sort=arrival_time" -s -o /dev/null -w  "%{time_starttransfer}\n"; done
1.822116
1.578963
1.574983
1.562348
1.587852
1.547837
1.458274
1.505999
1.518844
1.454921
Levs-MBP:~ lev$ for i in {1..10}; do curl -g "http://localhost:4000/predictions?filter[route]=Red,Orange,Green-B,Green-C,Green-D,Green-E,Blue,Mattapan,741,742,743,751,749&include=schedule,stop,route,trip,vehicle&sort=arrival_time" -s -o /dev/null -w  "%{time_starttransfer}\n"; done …
```
=> Preload schedules for predictions

apps/api_web/lib/api_web.ex, apps/api_web/lib/api_web/endpoint.ex, apps/api_web/lib/api_web/plugs/request_track.ex, apps/api_web/lib/request_track.ex, apps/api_web/test/api_web/plugs/request_track_test.exs, apps/api_web/test/request_track_test.exs
At the moment, we don't know how many concurrent request clients are
making. This will allow us to gather some data.
=> feat: track the number of concurrent requests

apps/api_web/config/config.exs, apps/api_web/lib/api_web/router.ex, apps/api_web/test/api_web/controllers/facility_controller_test.exs, apps/api_web/test/api_web/controllers/live_facility_controller_test.exs, apps/api_web/test/api_web/controllers/route_pattern_controller_test.exs
This also cleans up the Swagger documentation to use the new URLs for
LiveFacility and RoutePattern.
=> feat: make 2019-07-01 the default version

apps/api_web/lib/api_web/event_stream.ex, apps/api_web/test/api_web/event_stream_test.exs, apps/events/lib/events/gather.ex, apps/events/test/events/gather_test.exs, apps/state/lib/state/alert.ex, apps/state/lib/state/prediction.ex, apps/state/lib/state/server.ex, apps/state/lib/state/trip.ex, apps/state/lib/state/trip/added.ex, apps/state/lib/state/vehicle.ex, apps/state/test/state/route_test.exs, apps/state/test/state/trip_test.exs, apps/state_mediator/config/test.exs
Changes to improve the memory usage of the API
- when using Gather to wait for multiple pieces of data from the GTFS parsing, erase the data once all of it is received (rather than keeping it in the process memory)
- Hibernate (run GC and pause the process) most of the Server processes (as they only receive messages during startup)
- Hibernate EventStream processes to cleanup memory between sending
=> improved memory usage

apps/api_web/lib/api_web/controllers/alert_controller.ex, apps/api_web/lib/api_web/controllers/facility_controller.ex, apps/api_web/lib/api_web/controllers/line_controller.ex, apps/api_web/lib/api_web/controllers/live_facility_controller.ex, apps/api_web/lib/api_web/controllers/prediction_controller.ex, apps/api_web/lib/api_web/controllers/route_controller.ex, apps/api_web/lib/api_web/controllers/route_pattern_controller.ex, apps/api_web/lib/api_web/controllers/schedule_controller.ex, apps/api_web/lib/api_web/controllers/service_controller.ex, apps/api_web/lib/api_web/controllers/shape_controller.ex, apps/api_web/lib/api_web/controllers/stop_controller.ex, apps/api_web/lib/api_web/controllers/trip_controller.ex, apps/api_web/lib/api_web/controllers/vehicle_controller.ex, apps/api_web/lib/api_web/params.ex, apps/api_web/test/api_web/params_test.exs
Opening a PR to get feedback on this, since it's a bit hacky.
The atom `:invalid` is not an attribute of any model and is always an invalid sort, so trying to sort by any key which is not an existing atom will return: `{"errors":[{"code":"bad_request","detail":"Invalid sort key.","source":{"parameter":"sort"},"status":"400"}],"jsonapi":{"version":"1.0"}}`.
The alternative would be to change `filter_opts` to return something along the lines of `{:ok, _}` or `{:error, _}`, then modify ~15 calls to `filter_opts` to handle the error case. This would allow us to specify which sort key is invalid, though we don't actually do this now (as you can see from the response above). On the other hand, it would split the handling of bad sort keys across two different places depending on whether the bad …
=> Error on invalid sort which is not an existing atom

Dockerfile, rel/config.exs
Since Elixir 1.9 has releases built-in, Distillery has renamed some
modules/tasks in order to not conflict. We haven't updated to Elixir 1.9 yet,
so we rename our code to match Distillery.
=> fix: renames for Distillery 2.0

apps/api_web/config/prod.exs, apps/api_web/test/api_web/plugs/version_test.exs
I guess this didn't matter in earlier versions of either Elixir or Erlang,
but since upgrading we've lost some of these logs.
=> fix: ensure all metadata is logged properly

apps/api_web/config/config.exs, apps/api_web/config/prod.exs, apps/api_web/lib/api_web/rate_limiter.ex
It looks like clients who are rate limited hammer the server until their rate
limit expired. By adding a small delay to the requests, we can cut down on
how many requests they make which weren't going to be accepted anyways.
=> feat: wait small amount of time when rate-limiting requests

apps/state/test/state/schedule_test.exs
At least some failures seem to be happening because `State.RoutesPatternsAtStop` isn't returning anything, and it's needed for some `State.Schedule.filter_by` calls. I'll monitor whether this eliminates all of the spurious schedule test failures.
=> Fix spurious State.Schedule test failures

apps/state/lib/state.ex, apps/state/lib/state/server.ex
Appears much faster in local testing.
=> fix(Server): always use mnesia_dirty_index_match_object

apps/api_web/lib/api_web/controllers/shape_controller.ex, apps/api_web/lib/api_web/views/shape_view.ex, apps/api_web/test/api_web/views/shape_view_test.exs, apps/state/config/config.exs, apps/state/lib/state/shape.ex, apps/state/test/state/shape_test.exs, apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
- Store the full route_pattern name as the shape name, not just the destination.
- When clients on older versions query shape names, modify the names to remove the origins before sending the response.
=> Change shapes to use full route_pattern name on latest API version

apps/api_web/lib/api_web/templates/admin/accounts/key/form.html.eex
Currently the allowed domains for a key are only editable from the portal when logged in as the user who has that key. This PR allows admins to edit allowed domains as well.
=> Give admins the ability to edit CORS domains

apps/api_web/lib/api_web/api_controller_helpers.ex, apps/api_web/test/api_web/api_controller_helpers_test.exs
For example, queries like `/stops/?fields=name` would crash before.
=> fix: don't crash when given invalid fields

apps/parse/lib/parse/commuter_rail_departures/json.ex, apps/parse/test/parse/commuter_rail_departures/json_test.exs, apps/state/lib/state/trip/added.ex, apps/state/test/state/trip/added_test.exs
- Extract `route_pattern_id` when parsing `TripUpdate` from enhanced JSON.
- Include `route_pattern_id` in added trips created from predictions.
- Remove a number of `copy` calls in JSON parsing of trip updates in favor of calling Jason.decode with `strings: :copy`.
=> use the route_pattern_id from TripUpdate if present

rel/Dockerfile
From https://github.com/Yelp/dumb-init:
> dumb-init is a simple process supervisor and init system designed to run as
> PID 1 inside minimal container environments (such as Docker).
It properly forwards signals to the child process. I think this may be
related to issues we're seeing when we're terminating instances in Elastic
Beanstalk.
=> fix: use dumb-init for running the server

apps/state/lib/state/alert/hooks.ex, apps/state/test/state/alert/hooks_test.exs
Ticket: [alerts: multiple children with different activities are not combined](https://app.asana.com/0/810933294009540/1140769491475345/f)
Results from local vs prod:
[dev.txt](https://github.com/mbta/api/files/3659580/dev.txt)
[prod.txt](https://github.com/mbta/api/files/3659581/prod.txt)
Diff looks reasonable to me.
=> Group alerts and combine activities

apps/state/config/config.exs, apps/state/test/state/shape_test.exs, apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
**Asana Ticket:** [give Subway route patterns an origin in addition to the destination](https://app.asana.com/0/810933294009540/1140697116556421/f)
Comes w/ https://github.com/mbta/gtfs_creator/pull/550
=> Update subway route pattern names in the tests

apps/model/lib/model/vehicle.ex, apps/parse/lib/parse/vehicle_positions_json.ex, apps/parse/test/parse/vehicle_positions_json_test.exs, apps/state/lib/state/vehicle.ex, apps/state/test/state/vehicle_test.exs
- Parse labels from consist and store them as a list with the vehicle.
- Replace label `build_filters` with `do_post_search_filter` which matches individual labels in the consist as well as the label on the (entire) vehicle.
=> Vehicle: label query checks all labels in consist

apps/parse/lib/parse/vehicle_positions_json.ex, apps/parse/test/parse/vehicle_positions_json_test.exs
As we get the consist information as a separate message from the rest of the
vehicle information, it's possible to have a vehicle without a consist. Treat
that empty list the same as if we were not provided a consist at all.
=> fix: treat empty consist as nil

apps/fetch/lib/fetch/worker.ex, apps/fetch/test/fetch/worker_test.exs
These are happening a lot and filling up our logging.
=> fix: ignore spurious :ssl_closed in Fetch.Worker

apps/api_web/test/api_web/views/api_view_helpers_test.exs
Since they're modifying the global State tables, these tests can't run at the
same time as other tests.
=> fix: tests using State can't be async

apps/api_accounts/lib/api_accounts.ex, apps/api_accounts/test/api_accounts_test.exs, apps/api_web/lib/api_web/controllers/admin/accounts/key_controller.ex, apps/api_web/lib/api_web/router.ex, apps/api_web/lib/api_web/templates/admin/accounts/user/show.html.eex, apps/api_web/test/api_web/controllers/admin/accounts/key_controller_test.exs
In order to more easily rotate API keys for internal applications, this adds an administrative feature to create a clone of an existing key. The cloned keys shares the same attributes (rate limit, description, CORS) as the original key.
=> add ability to clone an existing key

.codecov.yml
That seems to be where it gets hung up.
=> fix: don't require CI to pass for Codecov

apps/api_web/lib/api_web/rate_limiter/memcache/supervisor.ex
`:random` always uses the same seed and so will always choose the same number (in this case 3) if it's being called each time in a new process.
`:rand` should actually use different (random) connections to Memcached each time.
=> Use :rand instead of :random

apps/api_web/lib/api_web/controllers/stop_controller.ex, apps/api_web/test/api_web/controllers/stop_controller_test.exs, apps/state/lib/state/stop.ex, apps/state/test/state/stop_test.exs
- If `filter[service]` and `date` are both present, we use the service_ids from `filter[service]` and ignore `date`.
- `filter[route]` must be present for either `filter[service]` or `date` to have any effect.
=> Filter /stops by service_ids

apps/state/lib/state/schedule.ex, apps/state/test/state/schedule_test.exs
For example:
/schedules/?filter[trip]=CR-Weekday-Fall-19-743&filter[stop]=South+Station is
returning two records, whereas it should only be returning one.
=> fix: only return 1 schedule for multi route trips

apps/state/config/config.exs
In partial fulfillment of **[create branch with new rating](https://app.asana.com/0/584764604969369/1142655599779855/f)**.
The Winter 2020 rating has a rebuilt Green-C schedule, which has included new shapes. We have overrides for the shapes/patterns that go to Lechmere, since Green-C service typically goes to North Station only. This pull request adds in the new `shape_id`s for those atypical trips.
Currently, not having those shapes is causing the new rating to fail in GTFS-creator: https://semaphoreci.com/mbta/gtfs_creator/branches/jf-winter-2020/builds/25.
=> Override for new Cleveland Circle - Lechmere shapes

apps/api_web/config/config.exs
Hopefully this will address the 502 errors we see from the load balancer.
From the [Cowboy docs](https://ninenines.eu/docs/en/cowboy/2.7/manual/cowboy_http/):
- request_timeout: "Time in ms with no requests before Cowboy closes the connection."
From the AWS load balancer documentation, some of the possible reasons for a
502 are:
- The load balancer received a TCP RST from the target when attempting to establish a connection.
- The target closed the connection with a TCP RST or a TCP FIN while the load
balancer had an outstanding request to the target. Check whether the
keep-alive duration of the target is shorter than the idle timeout value of
the load balancer.
I suspect that it's the latter. The default request timeout is 5000ms, so I
suspect something like this is happening.
1. Load …
=> fix: increase the request timeout

apps/state/lib/state.ex, apps/state/test/state_test.exs
- Adds new property test (copied from #166) which checks that sorting by time always works properly.
- The above property test may have failed when any of the integers selected for `times` is negative. This is fixed by converting `time` to an integer unix timestamp when sorting.
Note that in the absence of this conversion:
iex(1)> Enum.sort([DateTime.from_unix!(-1000), DateTime.from_unix!(1000)])
[~U[1970-01-01 00:16:40Z], ~U[1969-12-31 23:43:20Z]]
=> fix: compare timestamps as integers, not structs

apps/state/lib/state.ex, apps/state/test/state_test.exs
Predictions have DateTime values for `arrival_time` and `departure_time`, but Schedules use integer `seconds_after_midnight`, so `time` needs to be able to support both values.
=> fix: time sort supports seconds_after_midnight as well as datetimes

apps/parse/lib/parse/commuter_rail_departures/json.ex, apps/parse/test/parse/commuter_rail_departures/json_test.exs
This makes the code line up with the behavior from `trip_updates.ex`.
=> fix: Enhanced JSON prefers `:cancelled` statuses

apps/api_web/lib/api_web/swagger_helpers.ex
Asana ticket: [📚 stops: direction_id filter does not work with route_type](https://app.asana.com/0/584764604969369/1152021550580314/f)
=> doc: update description of filter[direction_id] to indicate it must be used with filter[route] to apply

apps/api_web/test/api_web/views/prediction_view_test.exs, apps/state/test/state/schedule_test.exs
Since filtering by trip/stop uses RoutePatternsAtStop, we need to ensure that
it's been updated before querying in the test cases.
=> test: ensure that RoutePatternsAtStop is updated

apps/state/config/config.exs
the Spring 2020 hastus export introduced a new shape (`810_0008`) for Green-B trips that ends in Lechmere. Adding this to `overrides`.
=> fix: add ignored shape (810_0008) for Green-B

apps/state/config/config.exs, apps/state/lib/state/helpers.ex, apps/state/lib/state/shape.ex, apps/state/test/state/helpers_test.exs, apps/state/test/state/shape_test.exs, apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
The new GTFS files will now have route patterns for the commuter rail generated based on the stops they visit and whether they're flag stops or leave early stops. Consequently, it's now possible for multiple trips with the same *shape* to have different *route patterns*, when previously there was a 1-to-1 correspondence between shape and route pattern.
=> feat: Handle new CR hash-based route patterns

apps/state/config/config.exs
Follow up to https://github.com/mbta/api/pull/193
These are new shapes associated with Green-D trips that have a start and/or end location not at one of the stops expected by the integration test.
Should address this validation error in this `gtfs_creator` build: https://semaphoreci.com/mbta/gtfs_creator/branches/fl-spring-2020/builds/19
=> fix: ignore Green-D shapes

apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
If there isn't service on the 101 for some reason, it's okay to not include 2725.
=> test: only check the stops on the 101 for valid dates

apps/state/config/config.exs, apps/state/lib/state/shape.ex, apps/state/test/state/shape_test.exs, apps/state/test/state_test.exs
In support of https://github.com/mbta/gtfs_creator/pull/763.
Checks for `shape_id`s _starting with_ the IDs listed in apps/state/config/config.exs, rather than requiring an exact match. This is so that new shapes that are generated from Disruptions will be properly prioritized.
(It's been a while since I've written any Elixir, so hopefully this all does what I think it does, particularly with the testing.)
=> Move shape prioritization to use starts_with

apps/state/config/config.exs
This quick patch seems to work for me locally; trying it on a branch on Semaphore as well.
=> fix: ensure Lechmere <-> Haymarket are not on Green-D

apps/state/lib/state/trip/added.ex, apps/state/test/state/trip/added_test.exs
Previously, we'd only create an Added trip if the schedule relationship was
`nil`, meaning scheduled. However, in some cases where the prediction data
doesn't line up with the current GTFS data, we can have scheduled trips but
no trip data from GTFS. In that case, we still want to provide a trip if
possible, so we treat it similarly to an ADDED trip, and generate a record
with the last predicted stop as the headsign.
=> fix: create an Added trip whenver we can't match the trip ID

apps/api_web/lib/api_web/api_view_helpers.ex, apps/api_web/test/api_web/controllers/prediction_controller_test.exs, apps/model/lib/model/prediction.ex, apps/state/lib/state/prediction.ex, apps/state/lib/state/trip.ex, apps/state/lib/state/trip/added.ex, apps/state/test/state/prediction_test.exs, apps/state/test/state/trip/added_test.exs
It appears that the issue the website is seeing with trips being returned as `null` is a race condition between when the predictions are available in `State.Prediction` and when the new trip is created in `State.Trip.Added`.
This PR makes three changes to address those issues:
1) adds a `trip_match?` flag to `Model.Prediction` which `State.Trip.Added` can use to only check predictions which we know didn't match a trip in GTFS.
2) Uses the `route_pattern_id` if it exists on the Prediction to shortcut all the complicated shape matching.
3) When including trips, adds a fallback to calculate the Added trip based on the appropriate predictions for that specific trip.
On dev-green, these changes take the `State.Trip.Added` processing time from 500-1500ms down to 10-25ms, which alone should cut …
=> speed up Trip.Added

apps/api_web/config/config.exs
In #217 we introduced the new 5/1 API version. Since it's almost May, we should get ready to make that the default.
=> chore: bump default API version to 2020-05-01

apps/api_web/lib/api_web/controllers/alert_controller.ex, apps/api_web/lib/api_web/swagger_helpers.ex, apps/api_web/mix.exs, apps/model/lib/model/alert.ex
* Several fields were nullable but not documented as such.
* The docs now explicitly state that, although all identifying fields on `InformedEntity` are nullable, at least one of them will be non-null.
* The previous minimal description of `InformedEntity` is replaced with the more detailed docs from its typespec, which had gone unused in the Swagger docs until now.
This also includes a small fix for a dev-only (?) build issue with the docs, which is explained in its own commit.
| Before | After |
|---|---|
|![](https://user-images.githubusercontent.com/394835/82381676-9e993000-99f8-11ea-9f2c-5391bb4f99d3.png)|![](https://user-images.githubusercontent.com/394835/82381786-c7b9c080-99f8-11ea-959b-e8ad36cce263.png)|
=> docs: Improve swagger docs for AlertResource

apps/api_web/lib/api_web/controllers/vehicle_controller.ex, apps/api_web/lib/api_web/views/vehicle_view.ex, apps/api_web/test/api_web/controllers/vehicle_controller_test.exs, apps/model/lib/model/vehicle.ex, apps/parse/lib/parse/vehicle_positions.ex, apps/parse/lib/parse/vehicle_positions_json.ex, apps/parse/test/parse/vehicle_positions_json_test.exs, apps/parse/test/parse/vehicle_positions_test.exs
Asana ticket: [👩‍👩‍👧‍👧 support crowding fields on Vehicle: `occupancy_status` enum ](https://app.asana.com/0/584764604969369/1171321386032805)
Changes:
* Add field `occupancy_status` to `Models.Vehicle`, using the values listed in the [GTFS realtime reference](http://gtfs.org/reference/realtime/v2/#enum-occupancystatus)
* Added logic to parse this field from a `VehiclePostion` entity (both JSON and protobuf)
* Added logic to `VehicleView` to return this value through the `VehicleController`
* Added documentation, just using the descriptions in the official reference
=> feat: add occupancy_status field to Vehicle

apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
Since Lechmere is closed (and Science Park is being bypassed), North
Station (place-north) is also an acceptable endpoint for Green-E.
=> test: also allow place-north as a Green-E endpoint

apps/state/config/config.exs
There's another new North Station shape that should be added to `prefix_overrides`. It's not causing our integration tests to fail, but it seems it's _likely_ causing Haymarket and North Station to be connected with Green Line-D in `dotcom`.
Working with this file also makes me wonder whether, since this is now `prefix_overrides` with prefixes, whether we can remove the full IDs of the individual shapes, and instead just put in `851_`, for example, to exclude all Riverside–North Station shapes.
=> fix: Exclude new North Station-Riverside shape

apps/api_web/lib/api_web/api_controller_helpers.ex
On 2020-06-15, we experienced some intermittent warnings due to slow response times. During normal times, no requests take longer than 10 seconds, so decreasing this timeout should be safe. At times when we're experiencing larger loads, this cuts off requests which are taking too many resources.
=> fix: decrease deadline to 10s

apps/api_web/lib/api_web/api_controller_helpers.ex, apps/api_web/lib/api_web/controllers/alert_controller.ex, apps/api_web/lib/api_web/controllers/facility_controller.ex, apps/api_web/lib/api_web/controllers/line_controller.ex, apps/api_web/lib/api_web/controllers/live_facility_controller.ex, apps/api_web/lib/api_web/controllers/route_controller.ex, apps/api_web/lib/api_web/controllers/route_pattern_controller.ex, apps/api_web/lib/api_web/controllers/service_controller.ex, apps/api_web/lib/api_web/controllers/shape_controller.ex, apps/api_web/lib/api_web/controllers/stop_controller.ex, apps/api_web/lib/api_web/controllers/trip_controller.ex, apps/api_web/lib/api_web/controllers/vehicle_controller.ex, apps/api_web/lib/api_web/router.ex, apps/api_web/lib/api_web/views/error_view.ex, apps/api_web/test/api_web/api_controller_helpers_test.exs
Previously, when passing an `accept` header of `text/event-stream` to a "show" endpoint (e.g. `/vehicles/[id]`) the API would return the resource once and close the connection. This first commit of this PR changes it to return a `406` response instead.
The second commit updates the swagger documentation to list `406` as a possible response. I wasn't sure if we intend to enumerate _all_ possible responses there, or just highlight the main ones, in which case we might not need or want to include it. However, when trying it locally, I ran into a lot of swagger errors:
```
Resolver error at paths./vehicles/{id}.get.responses.406.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/NotAcceptable does not exist in document
```
I guessed at `:NotAcceptable` …
=> Return 406 when attempting to stream a 'show' endpoint

apps/state/config/config.exs
**Asana Ticket:** Partial fulfilment of [🍁 create branch with new rating](https://app.asana.com/0/584764604969369/1187031945094559/f) and unblocking of https://github.com/mbta/gtfs_creator/pull/976
Adds new `shape_id`s to list of shapes to ignore in API prioritization:
- `811_0009` is an infrequent Boston College–North Station shape beginning in the upcoming Fall 2020 schedule.
- `881_0012` and `881_0013` are currently active for Prudential–North Station for only 4 weeks
=> chore: Ignore new, infrequent Green Line shapes

apps/state/config/config.exs
Related to [this](https://app.asana.com/0/584764604969369/1187036384840043/f) Asana ticket. Basically, `State.StopsOnRoute.by_route_ids` was including trips on the inbound Green-D `route_patterns` to North Station despite them being low typicality. I don't quite understand the underlying logic as well as I'd like, but it seems like we probably don't want to count Haymarket and North Station as stops on the D branch and it looks like manually excluding them in this way causes the gtfs_creator build to succeed with my changes in Arrow.
=> chore: ignore Green-D route patterns to North Station

apps/state/lib/state/trip/added.ex, apps/state/test/state/trip/added_test.exs
The stop fetched in `prediction_based_on_shape` could be nil, but later code didn't account for that possibility. Tests didn't catch this due to the data for the "unknown stop" test not including any shapes.
=> fix: nil crash in State.Trip.Added

apps/api_web/lib/api_web/controllers/prediction_controller.ex, apps/api_web/test/api_web/controllers/prediction_controller_test.exs
The `/predictions` endpoint allowed a `filter[date]` parameter, but didn't do anything with it. This is a backwards-incompatible change, since previously-working requests that included this parameter will now fail with a "no such filter" error.
This also clarifies the ambiguously-named `date` plug in the same controller, and makes it private since no code outside the controller called it.
**Note:** This is targeted at a separate release branch that introduces the new API version, currently a placeholder pending approval of the various branches that will go into this version.
=> fix: remove unused `date` filter from predictions

apps/api_web/lib/api_web/controllers/shape_controller.ex, apps/api_web/test/api_web/controllers/shape_controller_test.exs
We missed this when removing all fields other than `polyline` from shapes in d623868 and 657d4d7. This also fixes the Swagger docs still indicating that shapes had a `direction_id` field.
**Note:** This is targeted at a separate release branch that introduces the new API version, currently a placeholder pending approval of the various branches that will go into this version.
=> fix: remove `direction_id` filter from shapes

apps/state/config/config.exs
A couple of things to note:
1. From my debugging it looked like `place-lech` was being included as well, which didn't trigger the validation error but is obviously incorrect for now.
2. I also fixed a typo elsewhere in the map (a stray character in the `Green-D` key above).
=> fix: exclude Lechmere shuttle stops from Green-E

apps/parse/config/config.exs
From Michael G Chiang <mgchiang@us.ibm.com>:
> We found a change has occurred when the Woodland server was updated.
> From now on, the park-woodl-garage garage will be coming in as 'Woodland'.
=> fix: parse "Woodland" as `park-woodl-garage`

apps/state/config/config.exs
With the fall Commuter Rail schedules being deployed today, it turns out that an API change is needed for the Rockport Line shuttles to appear properly on dotcom:
There's been an existing branch `jf-rockport-extend`, that we've been using to test the fix for this shuttle before on dev-green. I've updated the branch to account for the new Manchester shuttles.
@losvedir Presuming I should rebase this branch on top of `master` now?
=> Overrides for Rockport Branch shuttles

apps/api_web/lib/api_web/controllers/prediction_controller.ex, apps/api_web/lib/api_web/controllers/schedule_controller.ex, apps/api_web/lib/api_web/swagger_helpers.ex, apps/api_web/test/api_web/controllers/schedule_controller_test.exs, apps/state/lib/state/schedule.ex, apps/state/test/state/schedule_test.exs
Asana ticket: [🍎 Provide a route_type filter for /schedules](https://app.asana.com/0/295455480314405/1198173974731337/f)
Adding a `route_type` filter to the schedule controller. Like the `route_type` filter in the predictions controller, I am requiring that one other filter be included. The implementation is likewise pretty similar.
=> feat: add route_type filter to schedule controller

apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
**Asana Ticket:** [🚝 Merge Rockport shuttle typicality fixes](https://app.asana.com/0/584764604969369/1199090851658061/f)
**Paired gtfs_creator PR:** https://github.com/mbta/gtfs_creator/pull/1050
Makes some adjustments to tests that are currently resulting in failing builds, as can be found in https://semaphoreci.com/mbta/gtfs_creator/branches/master/builds/452:
- Removes tests for checking for Foxboro, since we are not currently running trains to/from Foxboro anymore.
- Adjusts the test for checking for `CR-Franklin` trips through-routed via the Fairmount Line to look at `direction_id=0` instead of `direction_id=1`, since that's [the only direction we currently have this trains in the fall schedule](https://cdn.mbta.com/sites/default/files/route_pdfs/2020-fall/2020-11-02-cr-franklin-acce …
=> chore: Post-CR rating terminal, test adjustments

apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
**Relevant to:** [🚧 Plymouth closure Dec 12–14](https://app.asana.com/0/584764604969369/1199237221152083)
To guard against regression of a bug which caused Plymouth to not be present in the `CR-Kingston` stop list on weekends, this test asserted that it should be there on every day of service. However, this prevents us from implementing a disruption where the Kingston line actually will not stop at Plymouth for a few days, due to the station being closed.
This changes the test to check the stop list by service (instead of by date, which was translated to a service internally), and to only check services with a `schedule_typicality` less than 4. This allows services that don't stop at Plymouth (or Kingston) to pass validation as long as they're considered "atypical".
=> test: more flexible Kingston/Plymouth validation

apps/api_web/lib/api_web/controllers/alert_controller.ex, apps/api_web/lib/api_web/controllers/facility_controller.ex, apps/api_web/lib/api_web/controllers/prediction_controller.ex, apps/api_web/lib/api_web/controllers/route_controller.ex, apps/api_web/lib/api_web/controllers/route_pattern_controller.ex, apps/api_web/lib/api_web/controllers/schedule_controller.ex, apps/api_web/lib/api_web/swagger_helpers.ex, apps/api_web/test/api_web/swagger_helpers_test.exs, apps/state/lib/state/route_pattern.ex, apps/state/test/state/route_pattern_test.exs
**Asana:** [🐛 API route_patterns / stop filter](https://app.asana.com/0/584764604969369/1199540919582901)
We had originally intended that filtering route patterns by a parent station ID would return all route patterns serving its child stops, hence the existence of this `route_patterns_by_family_stops` function that was never called until now. Other endpoints with stop ID filters already work this way, except for `/facilities`, but that is currently irrelevant since we don't associate facilities with child stops.
=> fix: filtering route patterns by parent station ID

apps/health/config/config.exs, apps/health/lib/health/checkers/real_time.ex, apps/health/test/health/checkers/real_time_test.exs
Ticket: [[#869] 💳 mark instances unhealthy when they're unable to update vehicle locations / predictions](https://app.asana.com/0/584764604969369/1199189033001773/f)
Note that I would have liked to get the `timestamps_fetcher` and `current_time_fetcher` values via `Appication.compile_env` and just have different values for them in `config.exs` and `test.exs`, but unfortunately I need to change `current_time_fetcher` from one test to another, so `Application.get_env` it is. I'm open to suggestions for better ideas, though.
=> feat: mark instance unhealthy if vehicle or prediction data is stale

rel/env.sh.eex, semaphore/build_push.sh
Small tweaks to prepare for importing the API into terraform and deploying to Fargate via ECS.
Fargate abstracts away the underlying EC2 instance from us, so the `curl` command in the mix release startup fails. Looking at the test logs, it shows e.g. `api@ip-10-10-10-10`, (i.e. some IP address corresponding to our fargate instance), so that should still be enough to distinguish instances' requests from each other in the logs.
The other change relates to the way we model ECS in terraform; we have to specify an initial docker image, and then our deploys are free to change that without having to update our terraform config. However, for that initial image, it's our terraform convention to point to a tag `:latest` so spinning up a new AWS environment will start with the latest image.
=> chore: Update build/release scripts for fargate

semaphore/deploy_ecs.sh
A script to deploy to ECS in semaphore. There is a Dev Blue environment configured in there now, which can be deployed to using this script.
Most of the script is copied from our UML Mobility deployment process.
One change is the installation of a newer version of the AWS CLI tool. The one that's available by default in the API project of semaphore doesn't work because it doesn't handle the newer `secretOptions` parameter that allows the Splunk logdriver to access Secrets Manager. Rather than either installing this in `semaphore/setup.sh` or updating the API semaphore platform, I opted to just install it locally in this script, so the terraform/ECS stuff is totally self contained for now.
=> feat: Add script to deploy to ECS

apps/health/config/config.exs, apps/health/lib/health/checkers/ports.ex, apps/health/test/health/checkers/ports_test.exs
Asana: https://app.asana.com/0/116562505129567/1199678649889558
Normally, we have less than 100 open Ports at any one time. When we get an
unhealthy instance, we tend to see many more than that. This health check
will mark that instance as unhealthy so that AWS will replace the instance
for us.
=> feat: health check for the maximum number of open Ports

apps/state/config/config.exs
_This is a companion pull request to https://github.com/mbta/gtfs_creator/pull/1096._
**Asana Ticket:** [🚧 Littleton–Alewife weekday shuttles](https://app.asana.com/0/584764604969369/1199686637343555/f)
Introduces new API exceptions to ensure that upcoming Fitchburg Line shuttles properly appear on the dotcom timetable page, and so that the stops appear in the correct order.
=> fix: Do not ignore new Fitchburg Line shuttles

apps/state/config/config.exs
_NB: This is a companion pull request to https://github.com/mbta/gtfs_creator/pull/1105. This API pull request should be merged before the gtfs_creator one._
**Asana Ticket:** [🌷 Create branch with new bus/subway rating](https://app.asana.com/0/584764604969369/1199932228856346/f)
Adds new shape_ids to list of shapes to ignore in API prioritization:
- `811_0011` and `811_0012` are both infrequent Boston College–North Station shapes that will be used beginning in the upcoming Spring 2021 schedule. By not including them here, the API believes that Green B has North Station as a terminal, instead of Park Street (eg, https://semaphoreci.com/mbta/gtfs_creator/branches/jf-spring-2021-bus-subway/builds/12).
=> chore: Ignore new Green-B North Station patterns

apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
_Partial fulfilment of [🌷 *v1* spring CR schedule effective 4/5](https://app.asana.com/0/584764604969369/1200012291253476/f) and [💳 gtfs_creator uses HASTUS export for CR](https://app.asana.com/0/584764604969369/1199544279684311/f)._
Plymouth (aka, station `place-PB-0356`) on route `CR-Kingston` will no longer have service beginning with the Spring 2021 schedule. This commit removes the test that checks GTFS for service at that station, and is a prerequisite for the tasks mentioned above.
=> chore: Remove Plymouth from GTFS integration tests

apps/api_web/lib/api_web/controllers/shape_controller.ex
This bit of documentation confusingly referred to shapes having stops. The concept of "groups of trips that share a stop sequence" has since been moved from shapes to route patterns and the `representative_trip` relationship, and shapes are now just a polyline.
New version:
=> docs: bring ShapeResource up to date

apps/state/config/config.exs
**_Sibling of https://github.com/mbta/gtfs_creator/pull/1164, a GTFS-creator pull request that creates the relevant shuttle bus._**
**Asana Ticket:** [[Extra] 🌷 New CR schedule for Worcester Line](https://app.asana.com/0/584764604969369/1200132943599673/f)
Ensures that the patterns/shapes for a new service, the Newton Connection RailBus (part of the Worcester Line) on route ID `Shuttle-NewtonHighlandsWellesleyFarms`, aren't excluded from stops/stations in the Worcester Line timetable (linked below). The effect is that this adds Riverside and Newton Highlands to the website timetable, just as they are on the physical and PDF timetables.
Also enforces the ordering of stations with Newton Highlands and Riverside added to the mix.
Currently deployed to dev-green: …
=> chore: Add Worcester Line connection shuttle to timetable

apps/state/config/config.exs, apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
Asana task: [[Extra] 🚧 Fix Kingston Line API shape priorities](https://app.asana.com/0/584764604969369/1200153288405579/f)
Removes shape priority overrides for Kingston and Plymouth. Plymouth Station is now closed, and so the only shapes being used on `CR-Kingston` are those for South Station <-> Kingston, which the existing overrides de-prioritize.
Also removes overrides relating to Franklin Line route patterns no longer in use (the `route_pattern_id`s we generate for CR are based on a hash of the stops; the `CR-Franklin-Foxboro-` could still be relevant if the Foxboro Pilot resumes later this year since that's a change we could still make to the `route_pattern_id` in https://github.com/mbta/gtfs_creator/blob/master/gtfs_creator2/commuter_rail/reader.py#L97).
=> fix: Remove shape priority overrides for Kingston/Plymouth

apps/state/config/config.exs
**Asana task:** [[Extra] 🐛🚂 Forest Hills doesn't appear on Providence Line outbound timetable](https://app.asana.com/0/584764604969369/1200278941033220/f)
Ensures that Forest Hills gets shown on the outbound timetable for `CR-Providence` on MBTA.com to match the [PDF and physical schedules](https://cdn.mbta.com/sites/default/files/route_pdfs/2021-spring/2021-04-05-spring-providence-stoughton-v2-accessible.pdf).
This branch is up live on dev-green, and you can compare https://green.dev.mbtace.com/schedules/CR-Providence/timetable?date=2021-05-19 against https://www.mbta.com/schedules/CR-Providence/timetable?date=2021-05-19 to see the difference.
Note: This pull request is very similar to https://github.com/mbta/api/pull/358, just on a different line/stops.
=> chore: Add Forest Hills to Providence Line timetable

README.md, semaphore/test.sh
Removes our codecov.io integration ahead of closing our account.
We have an [asana task](https://app.asana.com/0/881264583703207/1200328232337696) to use our organization GitHub Action for testing (and code coverage), once we figure out the DynamoDB part of it.
=> chore: Remove dependence on codecov.io

apps/state/lib/state/alert.ex, apps/state/lib/state/server.ex, apps/state/lib/state/service.ex, apps/state/test/state/alert_test.exs, apps/state/test/state/server_test.exs
`State.Alert` maintains several "extra" ETS tables (beyond the Mnesia table that comes with `State.Server`), used to look up alerts by their active periods and informed entity attributes. Previously it kept these current by overriding `handle_new_state` to call the original, then update the tables. However, since the base `handle_new_state` contains the call to publish the `:new_state` event to subscribers, this resulted in a race condition:
1. A DiffServer subscribes to `/alerts?filter[route]=1`
2. The alerts JSON is updated to include a new alert affecting route `1`
3. The new alerts make their way to `State.Alert.handle_new_state`
4. `State.Alert` calls the original `handle_new_state`, which updates the Mnesia table and publishes the `:new_state` event
5. Meanwhile, the DiffServer …
=> Fix delayed events when streaming alerts

apps/state/config/config.exs, apps/state/lib/state/connecting_stops.ex, apps/state/lib/state/helpers.ex, apps/state/lib/state/routes_patterns_at_stop.ex, apps/state/lib/state/schedule.ex, apps/state/lib/state/stops_on_route.ex, apps/state/lib/state/trip/added.ex, apps/state/test/state/helpers_test.exs, apps/state/test/state/routes_patterns_at_stop_test.exs, apps/state/test/state/stops_on_route_test.exs
**Asana:** https://app.asana.com/0/584764604969369/1199912774871224
Certain trips can be "ignored" by the default logic that determines which stops are "on" a route. We created a config value to override this, but due to "ignored" being `true` internally, a `false` in this config meant "don't ignore", or "don't _not_ consider these trips" — a double negative that made the value confusing to read.
This inverts the meaning of the config, such that `true` means "_do_ consider these trips", and propagates that change through the rest of the code:
* "canonical" is used as the opposite of "ignored" (this also replaces "alternate" in `StopsOnRoute` specifically, which referred to the fact that originally alternate-route trips were the only "ignored" ones)
* `ignore_trip_route_pattern?` and …
=> refactor: remove double-negative in stops_on_route

apps/state/config/config.exs
_Follow-up to https://github.com/mbta/gtfs_creator/pull/1248:_
**Asana Ticket:** [🚧 Needham Heights–Forest Hills shuttle June 4](https://app.asana.com/0/584764604969369/1200362708685510/f)
For some reason, attempting to split off the `service_id`s for the Needham Line in https://github.com/mbta/gtfs_creator/pull/1248 results in the Hyde Park–Providence stops on the Providence Line to appear on the _outbound_ Needham Line timetable (located at https://www.mbta.com/schedules/CR-Needham/timetable). There is a nightly Providence Line train that is added to the Needham Line's timetable via `multi_route_trips.txt` in GTFS, but the additional non-Needham parallel stops have never appeared.
This pull request modifies the API configuration to make sure those stops are never output on …
=> fix: Ensure no Providence Line stops on Needham Line timetable

apps/state/config/config.exs
_NB: This is a companion pull request to https://github.com/mbta/gtfs_creator/pull/1250. This API pull request should be merged before the GTFS-creator one._
**Summary of changes**
**Asana Ticket:** [🏝 Compile GTFS for new rating](https://app.asana.com/0/584764604969369/1200335009876148/f)
Adds new `shape_id`s to list of shapes to ignore in API prioritization:
`811_0013` and `811_0014` are both infrequent Boston College–North Station shapes that will be used beginning in the upcoming Summer 2021 schedule. By not including them here, the API believes that Green B has North Station as a terminal, instead of Park Street. For example, in GTFS-creator, compare https://semaphoreci.com/mbta/gtfs_creator/branches/jf-summertime-2021/builds/11 and …
=> chore: Ignore Green-B North Station patterns for Summer 2021

apps/state/config/config.exs
_This is a companion pull request to https://github.com/mbta/gtfs_creator/pull/1256._
**Partial fulfilment of Asana ticket:** [[Extra] 🚧 CR schedule changes from June 28](https://app.asana.com/0/584764604969369/1200470065983391/f)
Permits the upcoming weekend Wachusett–Littleton/Route 495 shuttles to be factored into the API's stops-on-routes, for the purposes of properly rendering MBTA.com's timetable.
For example, before this branch is applied, the timetable would look like this, missing all stops north of Littleton/Route 495 to/from Wachusett:
Here are some similar PRs we've done to adjust Commuter Rail timetable listings: https://github.com/mbta/api/pull/333 and https://github.com/mbta/api/pull/358.
**This branch is currently live on dev-green for testing/verification: See example, …
=> fix: Include Wachusett–Littleton shuttles for Fitchburg stops-on-route

apps/state/config/config.exs
**In partial fulfilment of:** [🚧 South Weymouth–Braintree shuttles](https://app.asana.com/0/584764604969369/1200486623708256/f)
Permits the upcoming South Weymouth–Braintree shuttles to be factored into the API's stops-on-route for the Kingston Line, for the purposes of properly rendering [MBTA.com's timetable](https://www.mbta.com/schedules/CR-Kingston/timetable) for the relevant dates (July 17, 18, 23, 24, 25).
For example, before this branch is applied, the timetable would look like this, missing Braintree, since it is only served by the temporary shuttle on these days:
Once the branch is applied, however, the full shuttle schedule is properly rendered—in other words...**_voilà_**:
Here are some similar PRs we've done to adjust Commuter Rail timetable listings: …
=> fix: Include South Weymouth shuttles for Kingston stops-on-route

apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
**Asana task**: [[Extra] 🐛🍎 Green Line E terminal check during construction](https://app.asana.com/0/584764604969369/1200751963773400)
_This has a similar feel (and identical root cause) to https://github.com/mbta/gtfs_creator/pull/1281, which we had to do a week ago._
The Green Line E is only running between North Station and Brigham Circle from now through the end of August due to construction. This means no trains at Fenwood Road through Heath Street. Our GTFS feed currently only goes through August 28th, meaning there is no longer overlap with days when normal Heath Street trains will be running.
Since it has now been over 7 days since Green Line service to Heath Street has ended, there would no longer be any service in the published GTFS going out that far (we show schedules 0–7 days …
=> fix: Temp suppress Green-E terminal checks due to construction

apps/state/config/config.exs
_This is a copy of https://github.com/mbta/api/pull/394, but with the Haverhill Line and instead; see a little bit more there._
**In partial fulfilment of:** [[Extra] 🚧 Weekend Haverhill/Ballardvale–Malden shuttles](https://app.asana.com/0/584764604969369/1200753024082095/f)
This branch is currently live on dev-green for testing/verification: See example, https://green.dev.mbtace.com/schedules/CR-Haverhill/timetable?date=2021-08-15.
Permits the upcoming Haverhill/Ballardvale–Malden Center shuttles to be factored into the API's stops-on-route for the Haverhill Line, for the purposes of properly rendering [MBTA.com's timetable](https://www.mbta.com/schedules/CR-Haverhill/timetable) for the relevant dates (August 13, 14, 15).
=> fix: Include Malden shuttles for Haverhill stops-on-route

apps/state/config/config.exs, apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
_This is a companion pull request to https://github.com/mbta/gtfs_creator/pull/1292. This API pull request must be merged in before the GTFS-creator one._
**Asana Ticket:** [🍁 Compile GTFS for new rating](https://app.asana.com/0/584764604969369/1200680137242741/f)
A few adjustments coinciding with the Fall 2021 bus/subway rating.
`chore: Restore Green-E terminal validation`
- This commit reverts https://github.com/mbta/api/pull/412.
`fix: Exclude new uncommon Green Line shapes when forming typical route`
- These have to do with new Green Line shapes introduced this rating, something that https://github.com/mbta/api/pull/384 happens https://github.com/mbta/api/pull/343 more https://github.com/mbta/api/pull/316 often https://github.com/mbta/api/pull/269 than …
=> chore: Adjustments for Fall 2021 bus/subway schedule

apps/state/config/config.exs
Adds route pattern prefix overrides for the Haverhill-Andover shuttles.
=> fix: add Haverhill-Andover shuttle route pattern prefix overrides

apps/state/config/config.exs
_This is pretty similar to https://github.com/mbta/api/pull/394 and https://github.com/mbta/api/pull/413, but with the Newburyport/Rockport Line instead; see a little bit more there._
**In partial fulfilment of:** [[Extra] 🚧 Lynn–North Station/Chelsea shuttles weekends](https://app.asana.com/0/584764604969369/1201029209336670/f)
Permits the upcoming Lynn–Chelsea/North Station shuttles to be factored into the API's stops-on-route for the Haverhill Line, for the purposes of properly rendering [MBTA.com's timetable](https://www.mbta.com/schedules/CR-Newburyport/timetable) for the relevant dates (25–26 September and again in October). I ended up having to hardcode the specific train patterns being run this weekend for reasons still to be determined—I'll file a separate task for better …
=> fix: Include new shuttles for Newburyport/Rockport stops-on-route

apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
_See also related pull request, https://github.com/mbta/gtfs_creator/pull/1344._
**Partial fulfilment of Asana ticket:** [[Extra] 🚧 ❎ GTFS: Change GL downtown terminals from Oct 24](https://app.asana.com/0/584764604969369/1201205998033951/f)
Adjusts GTFS integration tests to support new northern/eastern terminals along the Green Line that will begin to take effect on 24 October.
=> chore: Support Green Line downtown terminal realignment

apps/api_web/lib/api_web/controllers/alert_controller.ex, apps/api_web/lib/api_web/controllers/facility_controller.ex, apps/api_web/lib/api_web/controllers/line_controller.ex, apps/api_web/lib/api_web/controllers/live_facility_controller.ex, apps/api_web/lib/api_web/controllers/prediction_controller.ex, apps/api_web/lib/api_web/controllers/route_controller.ex, apps/api_web/lib/api_web/controllers/route_pattern_controller.ex, apps/api_web/lib/api_web/controllers/schedule_controller.ex, apps/api_web/lib/api_web/controllers/shape_controller.ex, apps/api_web/lib/api_web/controllers/stop_controller.ex, apps/api_web/lib/api_web/controllers/trip_controller.ex, apps/api_web/lib/api_web/controllers/vehicle_controller.ex, apps/api_web/lib/api_web/params.ex, apps/api_web/lib/api_web/views/trip_view.ex, apps/api_web/test/api_web/params_test.exs, apps/api_web/test/api_web/views/trip_view_test.exs
**Asana:** [🍎](https://app.asana.com/0/584764604969369/1201382502692999)
The `occupancies` relationship on Trips was only intended to be accessible when the client has opted into experimental features, but this restriction only worked when trips were accessed via the `/trips` endpoints. If loading trips via another resource's endpoints, such as `/schedules?include=trip.occupancies`, the restriction did not apply.
This patch addresses the issue in basically the same way we handle other "conditionally existing" relationships: if accessed indirectly, the request will still be allowed, but the relationship will not contain any data. This does not attempt to address the broader inconsistency that validation of the `include` parameter only works at the "top level" of the include tree.
**Note:** …
=> fix: better enforce restrictions on `occupancies`

.github/workflows/deploy-prod.yml
The deploy to the new ECS service [failed](https://github.com/mbta/api/runs/5309879271?check_suite_focus=true). The service in ECS is actually `api-prod` rather than just plain `api`.
=> fix: API prod service is api-prod

.github/workflows/deploy-prod.yml
One more issue with the deploy: the `deploy-ecs` action expected a docker tag based on a previous step: `docker-tag: ${{ steps.build-push.outputs.docker-tag }}`, but we didn't have a `build-push` step! We could also just calculate the tag ourselves and pass that in, without requiring the `build-push` step, but I checked other repos (glides and skate) and they do the `build-push` step even in prod, so I figured I'd be consistent with them.
And I deployed to prod using this branch and it [looks like it's going through](https://github.com/mbta/api/actions/runs/1889960742).
=> fix: ECS deploy needs build-push step

apps/state/config/config.exs
_This is a companion pull request to https://github.com/mbta/gtfs_creator/pull/1452, which is still pending._
**Partial fulfilment of Asana ticket:** [⚡️🚧 Newburyport Branch shuttles March–April](https://app.asana.com/0/584764604969369/1201724214628506/f)
Permits the upcoming Newburyport–Beverly 495 shuttles to be factored into the API's stops-on-routes, for the purposes of properly rendering MBTA.com's timetable. These shuttle buses [will replace Newburyport Branch service entirely for the next month](https://cdn.mbta.com/sites/default/files/route_pdfs/2022-winter/2022-03-05-newburyport-rockport-diversion-schedule.pdf), 24/7.
Without this API branch, the Newburyport Branch is omitted entirely from the website timetable on the dates this diversion is in effect. Below is a screenshot of …
=> chore: Newburyport Branch shuttles contribute to stops-on-route

.github/workflows/prod.yml
Previously, the prod deploy to EB relied on a previous dev deploy to have setup the "deployment package" ("Application Version" in the EB console). But now that dev goes to ECS, prod will have to do a couple of the steps that dev used to do.
=> fix: Deploy to Prod (EB)

apps/state/config/config.exs
**Asana Ticket:** [❎ Publish v1 static data for March 21 opening](https://app.asana.com/0/584764604969369/1201964847789047/f)
_Companion to the GTFS-creator pull request, https://github.com/mbta/gtfs_creator/pull/1464._
Prevents Science Park, Lechmere, and Union Square from showing up on the Green Line D or Green Line E [line diagrams on MBTA.com](https://green.dev.mbtace.com/schedules/Green-E/line). This matches the current desire for MBTA.com to not show GLX information pre-opening on the line pages before opening.
Of course, we'll still want to show the GLX stations on the site once it opens, so there will have to be another pull request and additional deploy Sunday/Monday.
=> chore: Supress GLX stops, shapes from dotcom pre-opening

apps/state/config/config.exs
**✅ DEPLOY DATE: Sunday.**
**Asana task**: [❎🍎 Allow GLX stations in stops-on-route](https://app.asana.com/0/584764604969369/1201979219156159).
Paired with https://github.com/mbta/gtfs_creator/pull/1474, this PR reverts the latter commit from the recent pull request https://github.com/mbta/api/pull/488 to accomplish the following:
- Science Park, Lechmere, and Union Square will be allowed to feature on the MBTA.com line page list of stops for `Green-E`.
- The `Green-E` shapes to/from Union Square will be allowed to feature on the MBTA.com line page map.
This branch is currently on dev-green as of time that is pull request is marked as ready for review, and its effects can be found [MBTA.com dev-green](https://green.dev.mbtace.com/schedules/Green-E/line). (I think the caches are still …
=> fix: Allow GLX stations to appear in stops-on-route

apps/state/config/config.exs
_This is a companion pull request to https://github.com/mbta/gtfs_creator/pull/1485._
**Asana Ticket:** [🚧 Newburyport shuttles for April](https://app.asana.com/0/584764604969369/1201990551245842/f)
Essentially a repeat of https://github.com/mbta/api/pull/483, but this time for the Newburyport Branch shuttles that will be running for the month of April (running to/from Salem instead of Beverly).
=> chore: April Newburyport shuttles contribute to stops-on-route

apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
_Related GTFS-creator pull request: https://github.com/mbta/gtfs_creator/pull/1535_
**Related Asana task:** [🏝 Summer CR rating effective May 23](https://app.asana.com/0/584764604969369/1202203324773368/f)
Now that the Rockport Branch of the Newburyport/Rockport Line will be going all the way to Rockport...the API's integration tests can believe otherwise.
=> chore: Adjust Rockport Branch GTFS integration test

apps/state/config/config.exs
**In support Asana task:** [🚧 Newburyport/Rockport weekend shuttles](https://app.asana.com/0/584764604969369/1202484209942534/f) and [🚧 Lowell Line weekend shuttles](https://app.asana.com/0/584764604969369/1202484209942527/f).
Ensures that the Anderson/Woburn–North Station shuttle bus routes and the Beverly–Wellington shuttle bus routes properly show up in the respective rail routes' timetable pages. Also ensures that Wellington is allow to show up on dotcom timetables as a station on the Newburyport/Rockport Line.
For PR review, this branch has been deployed to `dev-green`; you can see https://dev-green.mbtace.com/schedules/CR-Newburyport/timetable?date=2022-07-09 and https://dev-green.mbtace.com/schedules/CR-Lowell/timetable?date=2022-07-09 to double-check.
=> chore: Support upcoming CR shuttles in timetables

apps/state/config/config.exs
Companion pull request to https://github.com/mbta/gtfs_creator/pull/1596, which introduces the new route IDs `Shuttle-BeverlyNorthStationExpress` and `Shuttle-BeverlyNorthStationLocal`.
- This branch has been deployed to `dev-green`.
=> chore: Support new CR shuttle in timetable

apps/state/config/config.exs
**Asana Ticket:** [🚧 Expand OL Tufts Medical shuttle hours](https://app.asana.com/0/584764604969369/1202914864561737/f)
Small API pull request to resolve integration errors associated with https://github.com/mbta/gtfs_creator/pull/1641. This pull request should be merged before the GTFS-creator pull request.
=> chore: Suppress OL shuttles from regular rail stops

apps/state/config/config.exs
**Asana task:** [[Extra] 🚧 Resolve Green Line D/E typicality/line page issues](https://app.asana.com/0/584764604969369/1202939238140170/f)
Science Park, Lechmere, and Union Square become allowed to be returned as part of Green Line D's list of stops, as they are about to become permanently part of that Green Line branch.
As of time of writing, this API branch is deployed to `dev-green` in conjunction with https://github.com/mbta/gtfs_creator/pull/1648. You can view the output at these links:
- https://dev-green.mbtace.com/schedules/Green/line
- https://dev-green.mbtace.com/schedules/Green-D/line
=> chore: Allow Green Line D to show to Union Square

apps/state/config/config.exs
**Asana Ticket:** [🍁 🚧 Fall Rockport Branch shuttle buses](https://app.asana.com/0/584764604969369/1203085339778674/f)
Ensures that Rockport Branch stations continue to be shown on https://www.mbta.com/schedules/CR-Newburyport/timetable even after Rockport Branch trains stop serving the stations (and only shuttle buses serve them) from 17 October 2022.
=> chore: Support Rockport–Beverly shuttles on dotcom

apps/alb_monitor/lib/alb_monitor/monitor.ex, apps/alb_monitor/test/alb_monitor/monitor_test.exs, apps/api_web/config/prod.exs, apps/api_web/lib/api_web.ex, apps/api_web/lib/api_web/canary.ex, apps/api_web/lib/api_web/event_stream.ex, apps/api_web/lib/api_web/plugs/check_for_shutdown.ex, apps/api_web/lib/api_web/router.ex, apps/api_web/test/api_web/canary_test.exs, apps/api_web/test/api_web/event_stream_test.exs, apps/api_web/test/api_web/plugs/check_for_shutdown_test.exs
**Asana Ticket:** [Round three of 502 investigation](https://app.asana.com/0/881264583703207/1203193998678560)
This PR makes three main changes:
- have the ALBMonitor.Monitor process stop normally when it detects that the draining process has started
- add a Plug (`CheckForShutdown`) to notify connections (both long-running and short-term) that they should disconnect
- update `Canary` to monitor for both shutdown and draining, and trigger the disconnection process in both cases
In practice, what this means is that when draining starts, all existing connections start to be disconnected in order to be routed to other nodes. New connections can still be accepted, but they aren't kept open. Once the deregistration delay expires in the ALB Target Group, the node will be removed from the ALB …
=> gracefully shut down the API during deploys (no 502s)

apps/state/config/config.exs
**Asana Ticket:** [🍁 🚧 Fall Rockport Branch shuttle buses](https://app.asana.com/0/584764604969369/1203085339778674/f)
Ensures that South Station and Braintree are shown on https://www.mbta.com/schedules/CR-Greenbush/timetable, https://www.mbta.com/schedules/CR-Kingston/timetable, and https://www.mbta.com/schedules/CR-Middleborough/timetable after shuttle buses are activated between those two stations for the weekend of 3–4 December 2022.
=> chore: Surface Braintree–South Station CR shuttles

apps/state/lib/state/stop.ex
The existing behavior for `State.Stop.filter_by/1` when there is at least one filter is to run the filters one-at-a-time, filtering out any stops which were already present in the list.
If there's only a single filter, we don't need to do any of that extra
work: we can simply return the value from the single filter.
I came across this while looking at the API Slow Query report.
=> perf: special case searching with a single Stop filter

apps/state/config/config.exs
**Asana Ticket:** [🍎 [Extra] Surface Haverhill Line shuttles on dotcom timetable pages](https://app.asana.com/0/584764604969369/1203851622817031/f)
Helps fix this situation on MBTA.com by making sure that the shuttle bus routes are being considered by the API:
The branch is being deployed to `api-dev-green` as we speak, once it's ready, you could verify https://dev-green.mbtace.com/schedules/CR-Haverhill/timetable?date=2023-02-04 to ensure it doesn't look like...the screenshot above.
=> chore: Surface Haverhill–Reading shuttles on stops-on-route

.github/workflows/deploy-dev-blue.yml
**Asana Ticket:** [don't deploy automatically in forks](https://app.asana.com/0/584764604969369/1204089064359689/f)
Dev-blue automatically deploys, but this shouldn't happen in forks. This adds a check to the job to ensure that it only runs in the `mbta` owned repository.
=> fix: don't deploy on forks

apps/state/lib/state/connecting_stops.ex
**Asana Ticket:** [🍎 Make Route 1 an official connection at Harvard](https://app.asana.com/0/584764604969369/1204332416083409/f)
If you look at https://www.mbta.com/schedules/Red before this PR is merged in, you _won't_ see a Route 1 connection at "Harvard".
On the contrary...if you go to https://dev-blue.mbtace.com/schedules/Red, you will see the connection at "Harvard" thanks to the small contribution made by this branch! Wonders!
=> chore: Add connection for Route 1 at Harvard

apps/state/config/config.exs
**Asana Ticket:** [🚧 Old Colony Lines shuttles, May weekends](https://app.asana.com/0/584764604969369/1204395229513140/f)
Ensures that trips using highly-atypical Middleborough/Lakeville Line route pattern (operating only between Braintree and Bridgewater) can be displayed on the MBTA.com timetable page on the weekend of 20–21 May 2023.
=> chore: Display Bridgewater–Braintree trains on timetable

apps/state/config/config.exs
**Asana Ticket:** [🚧 Lowell–Wilmington shuttles, Jun 3–4](https://app.asana.com/0/584764604969369/1204487765838992/f)
=> chore: Display Wilmington–Lowell trains on timetable

.gitignore, apps/api_web/lib/api_web/controllers/vehicle_controller.ex, apps/api_web/lib/api_web/swagger_helpers.ex, apps/api_web/lib/api_web/views/vehicle_view.ex, apps/api_web/test/api_web/controllers/vehicle_controller_test.exs, apps/model/lib/model/vehicle.ex, apps/model/lib/model/vehicle/carriage.ex, apps/parse/gtfs-realtime.proto, apps/parse/lib/parse/vehicle_positions.ex, apps/parse/lib/parse/vehicle_positions_json.ex, apps/parse/test/parse/vehicle_positions_json_test.exs, apps/parse/test/parse/vehicle_positions_test.exs
**Asana Ticket:** [👥🍎 Surface OL crowding estimates through the API](https://app.asana.com/0/584764604969369/1204735400214299/f)
This adds a field `carriages` (formerly known as `multi_carriage_details`) to the API. 
A few details - 
1. `carriages` consists of a list of objects - so I have implemented a separate model to represent the object. 
2. To support extracting `multi_carriage_details` from the Protobuf file, I had to load the new version of the `.proto` file found in Concentrate production. 
3. I came up with some descriptions for the field and sub-fields - but we may want to get these officially sanctioned 😄
=> feat: add carriages field to vehicle

apps/state/config/config.exs
**Asana Ticket:** [🚧 Ashland–Framingham shuttles, from Aug 26](https://app.asana.com/0/584764604969369/1205206171279036/f)
**Asana Ticket:** [🚧 Walpole–Forge Park shuttles, Aug 19–20](https://app.asana.com/0/584764604969369/1205206171279032/f)
=> chore: Support upcoming CR shuttles on dotcom timetables

apps/api_web/lib/api_web/plugs/require_2factor.ex, apps/api_web/lib/api_web/router.ex, apps/api_web/lib/api_web/templates/client_portal/layout/footer.html.heex, apps/api_web/test/api_web/controllers/admin/accounts/key_controller_test.exs, apps/api_web/test/api_web/controllers/admin/accounts/user_controller_test.exs, apps/api_web/test/api_web/controllers/admin/session_controller_test.exs, apps/api_web/test/api_web/plugs/require_2factor_test.exs
**Asana Ticket:** [🍎 Force 2FA for API admins](https://app.asana.com/0/295455480314405/1205277400179415/f)
This PR also addresses [🍎 API "Login" and "Register" links should not appear if user is already logged in](https://app.asana.com/0/295455480314405/1205212005457786/f)
Adds a `Plug` that can restrict access to URLs until the user enables 2 factor authentication, and applies it to `/admin` routes. 
Updates footer behavior so that `USER_EMAIL` / `Log Out` is shown instead of `Login` / `Register` when the user is already in a logged-in session.
=> feat: block access to admin pages when 2fa is disabled

apps/api_web/lib/api_web/controllers/vehicle_controller.ex, apps/api_web/lib/api_web/swagger_helpers.ex, apps/api_web/lib/api_web/views/vehicle_view.ex, apps/api_web/test/api_web/controllers/vehicle_controller_test.exs, apps/model/lib/model/vehicle.ex, apps/parse/lib/parse/vehicle_positions_json.ex
**Asana Ticket:** [👥🔮 Surface car-level crowding data through RTR](https://app.asana.com/0/584764604969369/1204735391632694/f)
This fixes the 500 error when attempting to encode vehicles with carriages. It also adds carriages to the tests, and adds the remaining legal occupancy statuses.
=> fix: 500 when getting vehicle with OL crowding data

apps/state/config/config.exs
**Asana Ticket:** [[stub] 🚧 Haverhill–Reading shuttles, Sept 9–Oct 5](https://app.asana.com/0/584764604969369/1204332437060399/f)
A few very similar and recent PRs we've done for this same sort of thing, ensuring that the MBTA.com timetables show Commuter Rail shuttle buses:
- https://github.com/mbta/api/pull/662
- https://github.com/mbta/api/pull/623
- https://github.com/mbta/api/pull/611
=> chore: Support upcoming Haverhill Line shuttles on dotcom timetables

apps/api_web/lib/api_web/controllers/alert_controller.ex, apps/api_web/lib/api_web/views/alert_view.ex, apps/api_web/test/api_web/views/alert_view_test.exs, apps/model/lib/model/alert.ex, apps/parse/lib/parse/alerts.ex, apps/parse/test/parse/alerts_test.exs
**Asana Ticket:** [🍎 Add image fields to /alerts API responses](https://app.asana.com/0/584764604969369/1204624899415317/f)
Adds experimental Image and Image Alternative Text fields to Alerts. Image Alternative Text is a translated string type, which we already handle. Image is a localized image type, which works very similarly to translated strings. Both fields are nullable.
Reference for localized image type: https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-translatedimage
=> Adds image and image_alternative_text fields to Alerts

apps/state/config/config.exs, apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
**Asana Ticket:** [🚧 Splice together new Stoughton Branch shapes](https://app.asana.com/0/584764604969369/1205320592017665/f)
=> fix: Use IDs for Stoughton routes on Providence/Stoughton line for Fall 2023 diversion

apps/health/config/config.exs
**Asana Ticket:** No ticket
Increase max ports to prevent the health checker from recycling pods before they are overloaded.
=> fix: increase max ports in health checker

apps/state_mediator/lib/state_mediator.ex, apps/state_mediator/lib/state_mediator/mqtt_mediator.ex
**Asana Ticket:** [test handling of failures/restarts with a multi-AZ broker](https://app.asana.com/0/584764604969369/1205632203703839/f)
no ticket. prevents logging the MQTT broker password into Splunk.
Also reconnects more quickly (See mbta/concentrate#309).
=> fix(mqtt): store password as a 0-arity function to prevent logging

.github/workflows/deploy-dev-blue.yml, .github/workflows/deploy-dev-green.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
**Asana Ticket:** [Update application repos to use the new version of the GitHub action(s) (v2 tag)](https://app.asana.com/0/1113179098808463/1205367032564122/f)
This PR updates the deploy workflow to use v2 of the `build-push-ecr` and `deploy-ecs` actions. These updated actions assume an IAM role instead of relying on long-lasting AWS keys for an IAM user
=> Chore: Update actions to v2 and assumed role

.tool-versions, Dockerfile
Updating Erlang to a version that works on Sonoma
=> chore: bump erlang/elixir to sonoma friendly versions

.gitignore, .tool-versions
**Asana Ticket:** No ticket
* Add poetry back to .tool-versions
If poetry was intentionally removed from .tool-versions, I could instead update the README to remove the line `Run asdf plugin-add poetry to add Poetry plugin`.
* Add local dynamodb metadata file to .gitignore
- **NOTE** on undocumented step: For the local dynamoDB setup, I needed to install java on my machine. I installed java globally via asdf. I didn't add instructions to the api_accounts/README but I could if anyone felt strongly about it.
=> chore: first time setup updates: poetry in .tool-versions and dynamodb file in .gitignore

apps/api_web/test/api_web/controllers/route_pattern_controller_test.exs
**Asana Ticket:** No ticket
I have a PR to merge but CI is failing. I looked at this briefly.
Service ids were duplicated across tests, so if they're running concurrently then that could create unexpected results.
I did have to add the State.Service.new_state call after updating the ids, if that's expected then this fix seems fine to me.
=> test: fix route_pattern_controller tests with explicit service defs

apps/api_web/lib/api_web/api_view_helpers.ex, apps/api_web/lib/api_web/controllers/admin/accounts/key_controller.ex, apps/api_web/lib/api_web/rate_limiter.ex, apps/api_web/lib/api_web/templates/admin/accounts/key/form.html.heex, apps/api_web/lib/api_web/templates/admin/accounts/user/show.html.heex, apps/api_web/lib/api_web/templates/client_portal/portal/index.html.heex, apps/api_web/test/api_web/controllers/admin/accounts/key_controller_test.exs, apps/api_web/test/api_web/controllers/portal/portal_controller_test.exs, apps/api_web/test/api_web/views/api_view_helpers_test.exs
**Asana Ticket:** [🍎 Adjust v3 API Admin Panel "edit" section to allow adjusting per-minute limit](https://app.asana.com/0/1205718273834959/1205807844528810)
This updates the admin edit key form to show the limit as a per-minute limit instead of a daily limit. The admin view for viewing keys already displays the request limit as a per-minute limit in production. The backend stores the limit as a daily limit.
This hard-codes the portal and admin views to show a key's limit as its per minute limit, ignoring the configured interval for clearing the limit. Production is configured to have a clear_interval of one minute (60,000 ms), meaning a per-minute limit.
There's a bit of complexity with our rate limiter that we have in part to allow tests to configure a shorter clear_interval. We have …
=> feat: allow admins to set API key limit by minute

apps/api_web/lib/api_web/controllers/prediction_controller.ex, apps/api_web/lib/api_web/controllers/route_pattern_controller.ex, apps/api_web/lib/api_web/controllers/stop_controller.ex
The Swagger spec doesn't support multiple types or required / nullable flags. Some vendors support x-nullable. So, I use that so that fields appear in a generated client.
```elixir
MBTA.Api.Stop.api_web_stop_controller_show(client, "place-sstat")
|> Kernel.elem(1)
|> Map.get(:data)
|> Map.get(:attributes)
```
```elixir
%MBTA.Model.StopResourceAttributes{
wheelchair_boarding: 1,
vehicle_type: nil,
platform_name: nil,
platform_code: nil,
name: "South Station",
municipality: "Boston",
longitude: -71.055242,
location_type: 1,
latitude: 42.352271,
description: nil,
at_street: nil,
address: "700 Atlantic Ave, Boston, MA 02110"
}
```
=> Change string | null type definitions

gem.deps.rb
chore: remove unused gem.deps.rb
**Asana Ticket:** [[extra] remove unused gem.deps.rb in API](https://app.asana.com/0/584764604969369/1205953777846444/f)
Pronto is no longer used in this repo.
=> chore: remove unused gem.deps.rb

apps/api_web/lib/api_web/controllers/stop_controller.ex
**Asana Ticket:** none
Noticed this while looking at the Swagger documentation and figured I'd just fix it. It appears to not have been caught in #61.
(I don't know for how long it's been the case, but there's a DynamoDB-local Docker image that makes getting the unit tests to work locally a lot easier; I can add a reference to that to `apps/api_accounts/README.md` if it'd be helpful to.)
=> fix: add 3 to stop location type enum

.github/workflows/asana.yml
fix: use shared Asana workflow that ignores Dependabot PRs
**Asana Ticket:** [[extra] fix Asana workflow in API](https://app.asana.com/0/584764604969369/1205953777846442/f)
Updates the Asana workflow to call the shared version. This should fix the failures on Dependabot PRs.
=> fix: use shared Asana workflow that ignores Dependabot PRs

apps/api_web/lib/api_web/endpoint.ex, apps/api_web/lib/api_web/plugs/authenticate.ex, apps/api_web/lib/api_web/plugs/clear_metadata.ex, apps/api_web/test/api_web/plugs/authenticate_test.exs, apps/api_web/test/api_web/plugs/clear_metadata_test.exs
Bandit keeps processes alive between requests, so we need to manually
clear the metadata to avoid it being kept between requests.
`curl -H "mbta-version: 2017-11-28" "http://localhost:4000/alerts/" "http://localhost:4000/alerts/?api_key=__configure_me__"`
```
2024-01-12 12:13:25.961 request_id=F6mo3h-7OA5-ItAAABqE api_key=anonymous api_version=2017-11-28 records=101 ip=127.0.0.1 pid=<0.1462.0> [info] state=set duration=56.644 status=200 params={} path=/alerts/ method=GET format=json-api controller=ApiWeb.AlertController action=index
2024-01-12 12:13:26.108 request_id=F6mo3ivHCwp-ItAAAAkn api_key=__configure_me__ api_version=2017-11-28 records=101 pid=<0.1462.0> [warning] state=set duration=1.072 status=403 params={} path=/alerts/ method=GET
```
```
2024-01-12 12:12:50.735 …
```
=> fix: clear Logger.metadata between requests

apps/state/config/config.exs
**Asana Ticket:** [[extra] Date Filter Hiding Stop from End Point](https://app.asana.com/0/584764604969369/1206469190651881/f)
I was able to fix the issue reported locally by updating the state config to include the current route_pattern for the two trips including Forest Hills (https://api-dev.mbtace.com/trips/AMTKSchCh651068-841 and https://api-dev.mbtace.com/trips/AMTKSchCh651474-839). We do have an extended disruption on CR-Providence relating to Amtrak that affects these trips. I'm not certain if that specifically caused the change in the route_pattern_id. 
I also [started a slack thread](https://mbta.slack.com/archives/C06CAP4N91C/p1707233921986039) about this configuration vs. the canonical GTFS work in gtfs_creator.
=> fix(stops): add updated route_pattern for CR-Providence that includes Forest Hills

apps/state/config/config.exs
**Asana Ticket:** Related to https://app.asana.com/0/1205718273834959/1206523362232788/f
Added stop IDs from green line shuttle to stops on route to fix test failure.
=> chore: GL-D shuttle stops not on route

apps/api_accounts/lib/api_accounts.ex, apps/api_accounts/lib/api_accounts/changeset.ex, apps/api_accounts/lib/api_accounts/dynamo.ex, apps/api_accounts/test/api_accounts/changeset_test.exs, apps/api_accounts/test/api_accounts/dynamo_test.exs, apps/api_accounts/test/api_accounts/notifications_test.exs, apps/api_accounts/test/api_accounts/table_test.exs, apps/api_accounts/test/api_accounts/user_test.exs, apps/api_accounts/test/api_accounts_test.exs, apps/api_web/test/api_web/controllers/admin/accounts/key_controller_test.exs, apps/api_web/test/api_web/controllers/admin/accounts/user_controller_test.exs, apps/api_web/test/api_web/controllers/admin/session_controller_test.exs, apps/api_web/test/api_web/controllers/portal/session_controller_test.exs, apps/api_web/test/api_web/controllers/portal/user_controller_test.exs, apps/api_web/test/api_web/plugs/cors_test.exs, apps/api_web/test/api_web/plugs/fetch_user_test.exs, apps/api_web/test/support/conn_case.ex, apps/api_web/test/support/fixtures.ex
Our e-mail validation library doesn't validate `@mbta.com` while on the VPN:
```
iex(1)> EmailChecker.valid?("pswartz@mbta.com")
false
```
=> test: switch to using `@example.com` so e-mails work on the VPN

apps/state/config/config.exs
fix: add stops_on_route overrides for CR-Worcester 2024-03-02
gtfs_creator PR: https://github.com/mbta/gtfs_creator/pull/2345
=> fix: add stops_on_route overrides for CR-Worcester 2024-03-02

apps/state/config/config.exs
fix: route pattern prefix for FraminghamSouthStationExpress
=> fix: route pattern prefix for FraminghamSouthStationExpress

apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
**Asana Ticket:** [🌷 Compile GTFS/ODS for new rating](https://app.asana.com/0/584764604969369/1206709127592083/f)
Resolves [this](https://github.com/mbta/gtfs_creator/actions/runs/8348773960/job/22851499137?pr=2364#step:15:822) validation error in the new rating, accepts both variants so we can quit flip-flopping between them depending on which is running.
=> fix: update validation to accept both forms of wickford junction

apps/state/config/config.exs
**Asana Ticket:** [🐛 🍎 Remove Pawtucket/Central Falls from Needham Line timetables](https://app.asana.com/0/584764604969369/1206759998465919/f)
=> fix: don't allow Pawtucket/Central Falls to appear on CR-Needham

apps/state/config/config.exs
**Asana Ticket:** [[extra] Incorrect order for Haverhill inbound stops](https://app.asana.com/0/295455480314405/1206921643035351/f)
=> fix: North Wilmington before reading in inbound direction

apps/state/config/config.exs
**Asana Ticket:** [🚧🟣 CR Maffa: Reactivate Newburyport/Haverhill shuttles, May 18-19](https://app.asana.com/0/584764604969369/1207132658261229/f)
Add Shuttle-NorthStationReading-0- to populate intermediate stops.
=> add Shuttle-NorthStationReading

apps/state/config/config.exs
**Asana Ticket:** [🚧🟣 [chore] Reactivate CR Bridgewater diversion for May 18](https://app.asana.com/0/584764604969369/1207290576950053/f)
=> fix: middleborough lines not being used for StopsOnRoute

apps/health/lib/health/checkers/run_queue.ex
**Asana Ticket:** [🍎 [Investigate] API 500 responses](https://app.asana.com/0/584764604969369/1207091416142835/f)
We have been talking about increasing the allowed run_queue length for our health check for some time. Given that there was brief service instability during this incident and the health checks started failing due to the run_queue length only, we can try upping the allow run_queue length.
The health check will still fail if the real-time request latency > 15 minutes or our State servers return empty data.
=> health: increase max run_queue length to 100

apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
NO TICKET
Haverhill is disrupted for the foreseeable future. "Bradford" is now the valid start of train service in the inbound direction.
=> start point changed to 0325

apps/state/config/config.exs
**Asana Ticket:** [🚧🟣 CR-Franklin weekend closure: Forge Park/495 to Walpole (August 17-18)](https://app.asana.com/0/1204473309455397/1207955522012163/f)
=> fix: prevent Franklin shuttles from ending up on Fairmount StopsOnRoute

apps/state/config/config.exs
**Asana Ticket:** [🚧🟢 GLD Weekend Closure: Kenmore to Newton Highlands (10/5-6)](https://app.asana.com/0/584764604969369/1208318959790287/f)
Fixes the validation failure in https://github.com/mbta/gtfs_creator/pull/2656
=> fix: don't consider disrupted route patterns for Green-C

apps/api_web/lib/api_web/views/alert_view.ex, apps/api_web/test/api_web/views/alert_view_test.exs
**Asana Ticket:** [🍎 Surface 'duration_certainty' in v3 API](https://app.asana.com/0/295455480314405/1207944069300404/f)
https://api-v3.mbta.com/alerts?fields[alert]=duration_certainty contains no actual duration_certainty values, because #828 was missing this piece. I've checked that this causes duration_certainty values to be returned.
=> fix: add duration_certainty to AlertView

apps/api_web/lib/api_web/views/prediction_view.ex, apps/api_web/test/api_web/controllers/trip_controller_test.exs, apps/api_web/test/api_web/views/prediction_view_test.exs, apps/api_web/test/api_web/views/schedule_view_test.exs
**Asana Ticket:** [🍎 Make prediction_ids for multi-route trips unique](https://app.asana.com/0/295455480314405/1208355953149037/f)
=> fix: prediction ids should be unique by route, for multi-route trips

apps/api_web/lib/api_web/controllers/route_controller.ex, apps/api_web/lib/api_web/views/agency_view.ex, apps/api_web/lib/api_web/views/route_view.ex, apps/api_web/test/api_web/controllers/route_controller_test.exs, apps/model/lib/model/agency.ex, apps/parse/lib/parse/agency.ex, apps/parse/test/parse/agency_test.exs, apps/state/lib/state.ex, apps/state/lib/state/agency.ex, apps/state/test/state/agency_test.exs, apps/state_mediator/lib/gtfs_decompress.ex
**Asana Ticket:** [[extra] [external] 🍎 Include agency_id in route responses](https://app.asana.com/0/584764604969369/1207163463172452/f)
The basic approach here actually ended up being fairly similar to commuter rail occupancies, in that there's a relationship from routes to agency but no `/agency` router or endpoint. One important difference is that since the only important information for this ticket at least is the ID, it's not possible to `include` an agency. I'm welcome to feedback on this, though, since I don't think it would be too much additional effort to parse out the additional agency fields and surface them via `include` if we wanted to.
I also updates the Swagger documentation a little bit to reflect the existing `line` and `route_patterns` relationships on routes. I think …
=> Provide agency information for route

apps/api_web/lib/api_web/views/status_view.ex, apps/api_web/test/api_web/controllers/status_controller_test.exs, apps/state/lib/state/metadata.ex, apps/state/test/state/metadata_test.exs
**Asana Ticket:** [🍎 Add route_patterns to the status V3 API endpoint](https://app.asana.com/0/584764604969369/1207518243385316/f)
This was pretty straightforward from just following the example of the other GTFS static-sourced states in the `/status` endpoint.
=> feat: include route_pattern information in /status

apps/state/lib/state/metadata.ex
**Asana Ticket:** [🍎 Look into /stops updating too frequently in v3 API /status endpoint](https://app.asana.com/0/1203810889612417/1207632677426964/f)
Upon examination, it turned out that the `Stop` state is implemented a bit differently from most of the other states, in that the process that actually `use`-es `State.Server` and tracks the state in an ETS table isn't `State.Stop` but `State.Stop.Cache`. The `State.Metadata.last_updates/1` function returns the result of `DateTime.utc_now/0` if no timestamp is found in ETS, so because we were looking for the last updated time of the wrong module we were always getting the current time.
=> fix: check correct ETS table for stop state last updated

apps/state/lib/state/trip/added.ex, apps/state/test/state/trip/added_test.exs
**Asana Ticket:** [🍎 Adjust API headsign logic for ADDED trips ](https://app.asana.com/0/1204473309455397/1208725414468453/f)
=> feat: use last predicted stop as added trip headsign

apps/state/lib/state/trip/added.ex, apps/state/test/state/trip/added_test.exs
**Asana Ticket:** [🍎 Constraint "Adjust API headsign logic for ADDED trips" to subway/light rail](https://app.asana.com/0/1204473309455397/1208827733362237/f)
=> fix: only adjust headsign to last predicted stop on subway routes

apps/state/lib/state/vehicle.ex, apps/state/test/state/vehicle_test.exs
**Asana Ticket:** [🍎🐛 v3 API returning null direction_id in certain cases](https://app.asana.com/0/584764604969369/1209119722014888)
Problem: As described in the linked ticket, sometimes we return vehicles with `"direction_id": null`. We aren't sure why. I spent a couple of days looking into this issue and didn't make any progress.
Solution: We are adding logs for when an invalid `direction_id` is returned. Hopefully these can allow us to better ascertain what conditions lead to this happening.
=> fix(vehicles): add logging if a non-shuttle vehicle has a null direction_id

apps/api_accounts/config/dev.exs, apps/parse/lib/parse/commuter_rail_occupancies.ex, apps/state_mediator/config/config.exs, apps/state_mediator/lib/state_mediator.ex, apps/state_mediator/lib/state_mediator/s3_mediator.ex, apps/state_mediator/mix.exs, apps/state_mediator/test/state_mediator/s3_mediator_test.exs, config/runtime.exs, mix.exs
…s from S3
**Asana Ticket:** [🍎 API reads Commuter Rail Occupancy from S3 instead of Firebase](https://app.asana.com/0/inbox/1208877353871379/1209182129817552/1209276288985685/f)
Problem:
Keolis needs to decommission their Firebase feed
Solution:
We're having them move the contents of that Firebase feed to S3.
Tactically, I added `StateMediator` for S3 that fetches files via `ExAws`. I made a temporary change to handle a new format (for some reason `cTrainNo` is relabeled as `Trip Name`, but I'm going to hold off on making that more permanent until I hear back from Keolis about whether this change was intentional.
=> feat(commuter_rail_occupancies): read commuter rail occupancies from S3 instead of firebase

apps/state_mediator/config/test.exs, apps/state_mediator/lib/state_mediator.ex
**Asana Ticket:** N/A
Problem: We weren't using the app setting for commuter rail crowding S3 bucket / object
Solution: use the app setting for these values such that they can be configured via environment variable
=> fix(s3-mediator): crowding uses s3 bucket / object from settings

apps/state/config/config.exs
**Asana Ticket:** [🚧🟣 St Patrick's Day schedules (Sunday March 16)](https://app.asana.com/0/584764604969369/1209528804368385)
Per discussion of the linked ticket, we want to add an override to the stop ordering to prevent a validation error.
I have tested this out locally and confirmed that it prevents the error.
=> chore: sort South Station at the end for CR-Franklin direction 1

apps/api_web/lib/api_web/controllers/vehicle_controller.ex, apps/api_web/test/api_web/controllers/vehicle_controller_test.exs
**Asana Ticket:** [[extra] 🐛🍎 /vehicles endpoint returns non-revenue vehicles by default](https://app.asana.com/1/15492006741476/project/584764604969369/task/1210583050716110?focus=true)
The `revenue=REVENUE` filter was only being applied to the vehicles endpoint if at least one other filter was specified. This removes the check that one other filter is specified so that it is always filtered by default.
* Updated unit tests to confirm that only revenue vehicles are returned by default
* TODO: Verify locally or in a dev environment. At present, there are no non-revenue vehicles in the feed.
=> fix(VehicleController): Filter out non-revenue vehicles if no revenue filter specified
