- README.md
- apps/api_web/config/config.exs
- apps/api_web/config/prod.exs
- apps/api_web/lib/api_web.ex
`info` is the default level so we don't need a configuration for that.
> make the log level configurable

- apps/api_web/lib/api_web/controllers/route_pattern_controller.ex
Ticket: [api /route-patterns documentation doesn't include relationships examples](https://app.asana.com/0/810933294009540/1110659645781137)
> Fixing resource name in router pattern controller

- apps/api_web/lib/api_web/controllers/route_controller.ex
Ticket: [Remove include=stop from api /routes/{id}](https://app.asana.com/0/810933294009540/1110659645781132)
> Remove include=stop from api /routes/{id}

- apps/api_web/lib/api_web/controllers/live_facility_controller.ex
- apps/api_web/lib/api_web/controllers/trip_controller.ex
Ticket: [ensure that all filters and includes in swagger are correct](https://app.asana.com/0/295455480314405/1112070806726914/f)
> Adding missing incldues to swagger

- apps/api_web/config/config.exs
This was formerly #5 but GitHub closed my PR.
> change API key default to 2019-02-12

- .tool-versions
- apps/state/config/config.exs
- apps/state/lib/state/stops_on_route.ex
- apps/state/test/state/stops_on_route_test.exs
- apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
This lets us give a short chunk of ordering preference.
Fixes [Plimptonville out of order](https://app.asana.com/0/116562505129567/1112453530163240)
> allow passing overrides to the merge function

- .gitignore
- apps/api_web/lib/api_web/controllers/route_controller.ex
- apps/api_web/lib/api_web/controllers/route_pattern_controller.ex
- apps/api_web/lib/api_web/controllers/trip_controller.ex
- apps/api_web/lib/api_web/views/route_view.ex
- apps/api_web/lib/api_web/views/trip_view.ex
- apps/api_web/test/api_web/controllers/route_controller_test.exs
- apps/api_web/test/api_web/controllers/route_pattern_controller_test.exs
- apps/api_web/test/api_web/controllers/trip_controller_test.exs
- apps/api_web/test/api_web/views/trip_view_test.exs
- apps/model/lib/model/trip.ex
- apps/parse/lib/parse/trips.ex
- apps/parse/test/parse/trips_test.exs
- apps/state/lib/state/route_pattern.ex
- apps/state/lib/state/trip.ex
- apps/state/test/state/trip_test.exs
Ticket: [route_patterns endpoint, phase 2](https://app.asana.com/0/1113863852319980/1113893353356229)
1. Add route_pattern_id to trips (has one)
```bash
$ curl -s 'http://localhost:4000/trips?id=Boat-F1-2315-Long-Saturday' | jsonpp
{
"data": [
{
"attributes": {
"bikes_allowed": 1,
"block_id": "B-22",
"direction_id": 0,
"headsign": "Hingham via Hull",
"name": "",
"wheelchair_accessible": 1
},
"id": "Boat-F1-2315-Long-Saturday",
"links": {
"self": "/trips/Boat-F1-2315-Long-Saturday"
},
"relationships": {
"route": {
"data": {
"id": "Boat-F1",
"type": "route"
}
},
"route_pattern": {
"data": {
"id": "Boat-F1-2-0",
"type": "route_pattern"
}
},
"service": {
"data": {
"id": "Boat-F1-Saturday",
"type": "service"
}
},
"shape": {
"data": {
"id": "b0001",
"type": "shape"
}
}
},
"type": "trip"
}
], …
```
> route_patterns endpoint, phase 2

- apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
The same conditions are already checked when creating gtfs feeds
> Remove informed entity test from gtfs_test

- apps/api_web/config/config.exs
- apps/api_web/lib/api_web/controllers/alert_controller.ex
- apps/api_web/lib/api_web/controllers/facility_controller.ex
- apps/api_web/lib/api_web/controllers/line_controller.ex
- apps/api_web/lib/api_web/controllers/live_facility_controller.ex
- apps/api_web/lib/api_web/controllers/prediction_controller.ex
- apps/api_web/lib/api_web/controllers/route_controller.ex
- apps/api_web/lib/api_web/controllers/route_pattern_controller.ex
- apps/api_web/lib/api_web/controllers/schedule_controller.ex
- apps/api_web/lib/api_web/controllers/service_controller.ex
- apps/api_web/lib/api_web/controllers/shape_controller.ex
- apps/api_web/lib/api_web/controllers/stop_controller.ex
- apps/api_web/lib/api_web/controllers/trip_controller.ex
- apps/api_web/lib/api_web/controllers/vehicle_controller.ex
- apps/api_web/lib/api_web/params.ex
- apps/api_web/lib/api_web/views/stop_view.ex
- apps/api_web/test/api_web/controllers/facility_controller_test.exs
- apps/api_web/test/api_web/params_test.exs
Ticket: [Create a new version to enable validation checking](https://app.asana.com/0/810933294009540/1112892656710275)
Without API key:
```bash
$ curl -s "http://localhost:4000/stops?id=place-alfcl&include=smth" | jsonpp
{
"errors": [
{
"code": "bad_request",
"detail": "Unsupported include(s): smth",
"source": {
"parameter": "include"
},
"status": "400"
}
],
"jsonapi": {
"version": "1.0"
}
}
```
With API Key version 2018-07-23:
```bash
$ curl -s "http://localhost:4000/stops?id=place-alfcl&include=smth&api_key=f9e9***6104b7" | jsonpp
{
"data": [
{
"attributes": {
"address": "Alewife Brook Pkwy and Cambridge Park Dr, Cambridge, MA 02140",
"description": null,
"latitude": 42.395428,
"location_type": 1,
"longitude": -71.142483,
"name": "Alewife",
"platform_code": null,
"platform_name": null, …
```
> New API version with filters/includes validation

- apps/parse/lib/parse/stops.ex
- apps/parse/test/parse/stops_test.exs
@jfabi looks like we also missed supporting the new stops in the API :/
> fix: support stops without locations

- apps/api_web/lib/api_web/controllers/facility_controller.ex
- apps/api_web/lib/api_web/views/facility_view.ex
- apps/api_web/test/api_web/controllers/facility_controller_test.exs
- apps/api_web/test/api_web/views/facility_view_test.exs
- apps/model/lib/model/facility.ex
- apps/parse/lib/parse/facility.ex
- apps/parse/test/parse/facility_test.exs
`short_name` is the `facility_short_name` from GTFS `facilities.txt`.
> Add short_name to facilities

- apps/api_web/lib/api_web/controllers/stop_controller.ex
Ticket: [API Swagger: location_types, bad extensions link](https://app.asana.com/0/810933294009540/450671048515595/f)
> Updating StopResource documentation

- apps/api_web/lib/api_web/api_controller_helpers.ex
- apps/api_web/lib/api_web/api_view_helpers.ex
- apps/health/lib/health/checkers/run_queue.ex
- apps/health/test/health/checkers/run_queue_test.exs
- apps/state/lib/state/server.ex
- mix.lock
> additional logging

- apps/api_web/lib/api_web/controllers/stop_controller.ex
- apps/api_web/lib/api_web/views/stop_view.ex
- apps/api_web/test/api_web/views/stop_view_test.exs
- apps/model/lib/model/stop.ex
- apps/parse/lib/parse/stops.ex
- apps/parse/test/parse/stops_test.exs
Asana ticket: [include new GTFS stop data](https://app.asana.com/0/810933294009540/1129153796213105/f)
> Add new stop fields (municipality, on_street, at_street, vehicle_type)

- apps/state/lib/state/trip.ex
- apps/state/test/state/trip_test.exs
Ticket: [keep trip information if it's used as a representative_trip_id](https://app.asana.com/0/810933294009540/1128638932210610/f)
> Don't filter trips by valid service any more

- apps/api_web/lib/api_web/controllers/prediction_controller.ex
- apps/api_web/test/api_web/controllers/prediction_controller_test.exs
- apps/state/lib/state/trip.ex
Asana ticket: [API: query predictions by route_pattern](https://app.asana.com/0/810933294009540/1128756751923940/f)
> Filter /predictions by route_pattern_id

- apps/state/lib/state/alert.ex
- apps/state/lib/state/facility.ex
- apps/state/lib/state/facility/parking.ex
- apps/state/lib/state/facility/property.ex
- apps/state/lib/state/line.ex
- apps/state/lib/state/prediction.ex
- apps/state/lib/state/route.ex
- apps/state/lib/state/route_pattern.ex
- apps/state/lib/state/schedule.ex
- apps/state/lib/state/server.ex
- apps/state/lib/state/service.ex
- apps/state/lib/state/shape.ex
- apps/state/lib/state/stop/cache.ex
- apps/state/lib/state/transfer.ex
- apps/state/lib/state/trip.ex
- apps/state/lib/state/trip/added.ex
- apps/state/lib/state/vehicle.ex
- apps/state/test/state/server_test.exs
Ticket: [rename `indicies` in State.Server](https://app.asana.com/0/810933294009540/1129357126602205/f)
> Renaming indicies to indices

- apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
We'll be having some work done on the Green Line, which will result in
Haymarket closing. For testing, we only compare the stops which exist to the
route order.
> fix: work around Haymarket closing

- README.md
- apps/parse/lib/parse/vehicle_positions.ex
- apps/parse/lib/parse/vehicle_positions_json.ex
- apps/parse/test/parse/vehicle_positions_json_test.exs
- apps/parse/test/parse/vehicle_positions_test.exs
- apps/state_mediator/config/config.exs
Replaces `VehiclePositions.pb` with `VehiclePositions_enhanced.json` and updates parser accordingly.
> Switch to using enhanced VehiclePositions JSON

- apps/state/config/config.exs
- apps/state/lib/state/helpers.ex
- apps/state/lib/state/stops_on_route.ex
- apps/state/test/state/helpers_test.exs
- apps/state/test/state/stops_on_route_test.exs
Pulled out of #114, but without the integration test changes. These should pass the existing tests, but have the right output with the new GTFS data.
> add overrides for new Foxboro service

- apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
Updates to the integration tests post #120 .
> test: add integration tests for Foxboro service

- apps/api_web/lib/api_web/controllers/status_controller.ex
- apps/api_web/lib/api_web/views/status_view.ex
- apps/api_web/test/api_web/controllers/status_controller_test.exs
- apps/state/lib/state/feed.ex
- apps/state/lib/state/metadata.ex
- apps/state/test/state/feed_test.exs
- apps/state/test/state/metadata_test.exs
Move `feed_version` into `feed` as `version` and add `start_date` and `end_date`.
> Add start_date and end_date to /status

- apps/state/lib/state/stops_on_route.ex
I've had a longstanding ticket to document how we calculate the lists of StopsOnRoute, so this is the first pass at that.
> doc: StopsOnRoute

- apps/api_web/lib/api_web/controllers/schedule_controller.ex
- apps/api_web/lib/api_web/views/schedule_view.ex
- apps/api_web/test/api_web/views/schedule_view_test.exs
- apps/model/lib/model/schedule.ex
- apps/parse/lib/parse/helpers.ex
- apps/parse/lib/parse/stop_times.ex
- apps/parse/lib/parse/vehicle_positions.ex
- apps/parse/test/parse/stop_times_test.exs
Asana ticket: [🍎 add headsign to the schedules API](https://app.asana.com/0/295455480314405/1159497818907390/f)
> Add `stop_headsign` to Schedule endpoint

- apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
Part of [the ticket](📅 June 22nd CR schedules & Gloucester Draw) to get new CR schedules in.
> fix: address Lowell validation issues

- apps/api_web/lib/api_web/controllers/prediction_controller.ex
Asana ticket: [🍎 better documentation of difference between `trip` for Prediction and Vehicle](https://app.asana.com/0/295455480314405/1182494433750450/f)
> docs: explain relation of predictions to trips vs. vehicles to trips

- apps/state/config/config.exs
Adjustment for Winter 2021 rating
> fix: deprioritize shape 811_0010 for Green-B

- .github/workflows/dev-green.yml
- .github/workflows/dev.yml
- .github/workflows/prod.yml
asana: https://app.asana.com/0/116562505129567/1200354670994292
> sample code for deploying to Elastic Beanstalk

- apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
**Asana:** [🚧 Remove old GL terminals from API tests](https://app.asana.com/0/584764604969369/1201227620034052)
> test: adjust assertions for new GL core terminals

- README.md
**Asana Ticket:** [📝🍎 Update API readme](https://app.asana.com/0/584764604969369/1201303330200926/f)
[Change mix command for running phoenix server to `mix phx.server` rather than `mix phoenix.server`]
> docs: Fix README.md for correct mix command for running Phoenix server

- .github/workflows/deploy-dev-green.yml
Have to update the GitHub Action to deploy to ECS, too!
> chore: Update dev-green deploys to ECS

- .github/workflows/deploy-dev.yml
Oops, syntax in #472 was a little bit off.
> fix: Deploy Dev workflow

- .github/workflows/deploy-prod.yml
Update the GitHub Action to deploy prod to ECS 🚀
> feat: Add prod deploy yaml script

- apps/state/lib/state/trip/added.ex
- apps/state/test/state/trip/added_test.exs
- apps/state/test/state/trip_test.exs
**Asana:** [🍎🐛 ADDED trips are marked accessible](https://app.asana.com/0/584764604969369/1202072678511513)
> fix: mark added trips as wheelchair-accessible

- apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
**Asana Ticket:** [[Extra] 🚧 Resolve Rockport Branch GTFS/API errors](https://app.asana.com/0/584764604969369/1203238967832696/f)
See also companion PR, https://github.com/mbta/gtfs_creator/pull/1703.
> fix: Suppress check while Rockport Branch closed Fall 2022

- apps/state/config/config.exs
- apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
**Asana Ticket:** [❎ Medford/Tufts Dec 12 opening in GTFS-static](https://app.asana.com/0/584764604969369/1203503515189544/f)
These changes are currently up on https://dev-blue.mbtace.com/ and have been vetted by the dotcom dev team, but an extra pair of eyes can't ~help~ hurt! Note that this pull request must be merged in before the related GTFS-creator, https://github.com/mbta/gtfs_creator/pull/1578.
> chore: Reconfigure Green Line branches for Medford/Tufts opening

- .tool-versions
Asana Ticket: [🍎 upgrade Poetry to 1.3.1](https://app.asana.com/0/881264583703207/1203656158386265/f)
> chore: update Poetry to 1.3.1

- apps/state/lib/state/prediction.ex
Asana Ticket: https://app.asana.com/0/881264583703207/1203656158386261/f
I did some quick investigation since most of the 10 slowest queries were of this form.
> perf: small tweak to improve `/schedules/?include=predictions` performance

- .github/workflows/deploy-dev-blue.yml
- .github/workflows/deploy-dev.yml
- .github/workflows/elixir.yml
- .tool-versions
**Asana Ticket:** [Setup GitHub Actions for nightly CI + dev deploy runs](https://app.asana.com/0/584764604969369/1203566390446223/f)
This adds a build and dev deploy workflow run every day at midnight.
> ci: added scheduled builds and fixes build

- apps/state/lib/state/connecting_stops.ex
- apps/state/lib/state/stop.ex
- apps/state/lib/state/stop/cache.ex
**Asana Ticket:** [🍎 Allow connecting_stops from ferry docks](https://app.asana.com/0/295455480314405/1203665082972638/f)
> feat: allow connecting_stops from ferry docks

- .github/workflows/asana.yml
- .github/workflows/elixir.yml
- apps/api_accounts/config/dev.exs
- apps/api_accounts/config/test.exs
**Asana Ticket:** [[extra] 🍎 fix failing tests after DynamoDB-local release](https://app.asana.com/0/584764604969369/1204958178756613/f)
This version requires a valid-ish AccessKey, per the notes in
[DockerHub](https://hub.docker.com/r/amazon/dynamodb-local).
> feat(ci): upgrade DynamoDB-local to version 2

- apps/state/config/config.exs
**Asana Ticket:** [[Extra] 🚧 Wachusett–Shirley shuttles](https://app.asana.com/0/584764604969369/1205501208153401/f)
> chore: Show Wachusett–Shirley shuttles on MBTA.com timetables

- apps/state/config/config.exs
> fix: exempt 9070154 from being part of Green-D

- apps/state/lib/state/connecting_stops.ex
**Asana Ticket:** [🚧🟣🐣 Lynn Interim Station - child stops](https://app.asana.com/0/584764604969369/1206105307715953/f)
> feat: connect old Lynn to Lynn Interim station

- apps/state/config/config.exs
**Asana Ticket:** [[extra] 🚧⛄ Rating adjustments (GLD schedule + Bus name change)](https://app.asana.com/0/584764604969369/1206145955881007/f)
> fix: ignore shape 8000023 for Green-D adjusted routes

- apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
**Asana Ticket:** [[🚝🐛][Extra] Resolve GTFS validation for CR-Providence](https://app.asana.com/0/584764604969369/1206362889032930/f)
Companion PR: https://github.com/mbta/gtfs_creator/pull/2299
> fix: CR-Providence validation around wickford

- scratch.exs
chore: add stuff to scratch.exs
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/mbta/api/pull/755).
* __->__ #755
* #754
> chore: add stuff to scratch.exs

- apps/api_web/lib/api_web/swagger_helpers.ex
**Asana Ticket:** No Ticket
Adds definitions for additional status fields used by subway crowding
> chore: update occupancy_status descriptions

- apps/api_accounts/README.md
- docker-compose.yml
chore(deps): add docker-compose.yml for DynamoDB Local
> chore(deps): add docker-compose.yml for DynamoDB Local

- apps/api_web/lib/api_web/controllers/alert_controller.ex
- apps/model/lib/model/alert.ex
No Asana Ticket. I just happened across this typo.
> fix: Fix a typo in the alert severity field description

- apps/state_mediator/test/state_mediator/integration/gtfs_test.exs
Asana Ticket: [🚧🟣 Spring 2024 Commuter Rail rating, starting May 20](https://app.asana.com/0/584764604969369/1207118646684817/f)
* Update tests to reflect new Spring rating from Keolis
> fix: add Providence/Stoughton shape for CR Rating Spring 2024

- apps/state/mix.exs
> fix: depend on proper directly

- .tool-versions
**Asana Ticket:** [[extra] 🍎 erlang 25.3.2.12](https://app.asana.com/0/584764604969369/1207405663588326/f)
Upgrades Erlang.
> chore: erlang 25.3.2.12

- apps/state/config/config.exs
**Asana Ticket:** [🚧🟣 CR Kingston, June 22-23](https://app.asana.com/0/1207213391093488/1207402531032543/f)
> Chore: Added halifax-kingston shuttle override

- .github/workflows/elixir.yml
**Asana Ticket:** [[extra] 🍎 allow running CI manually](https://app.asana.com/0/584764604969369/1207590623838327/f)
> feat(ci): allow running manually

- apps/api_web/lib/api_web/swagger_helpers.ex
**Asana Ticket:** No ticket
Found a couple links that were no longer functional, so I replaced them with working ones.
I bet there are more, but these were the only ones I checked.
> fix: Broken links

- .github/workflows/elixir.yml
> chore: bump version of upload-artifact

- apps/api_web/lib/api_web/controllers/route_controller.ex
- apps/api_web/lib/api_web/views/route_view.ex
- apps/api_web/test/api_web/controllers/route_controller_test.exs
- apps/api_web/test/api_web/views/route_view_test.exs
**Asana Ticket:** [🍎 Add listed_route filter to /routes resource](https://app.asana.com/1/15492006741476/project/1204473309455397/task/1207373205759001?focus=true)
> feat: add listed_route property and filter to routes
